function [commandVelocity, targetPosition, drone, landing] = ...
    refinedLandingController( ...
        drone, simulationTime, config)
%REFINEDLANDINGCONTROLLER Execute a stable multi-phase landing.
%
% Landing phases:
%
%   LANDING_APPROACH
%       Align position, altitude, and yaw above the landing pad.
%
%   LANDING_DESCENT
%       Descend while holding the configured landing yaw.
%
%   LANDING_FLARE
%       Reduce horizontal and vertical velocity near the ground.
%
%   TOUCHDOWN_VERIFY
%       Apply ground lock and verify stable contact.
%
%   COMPLETE
%       Hold the exact goal position and final heading.
%
% Explicit yaw control prevents wind and small horizontal corrections
% from rotating the drone during landing.

    %% Landing references
    goal = ...
        config.mission.goalPosition;

    landingYaw = ...
        config.landing.targetYaw;

    %% Enable explicit yaw control throughout landing
    drone.yawControlActive = true;

    drone.commandedYaw = ...
        landingYaw;

    %% Initialize landing diagnostics
    landing.phase = ...
        string(drone.landingPhase);

    landing.groundLockActive = false;

    landing.horizontalError = Inf;
    landing.verticalError = Inf;

    landing.yawErrorRadians = ...
        wrapAngleToPiLocal( ...
            landingYaw - drone.yaw);

    landing.yawErrorDegrees = ...
        rad2deg(landing.yawErrorRadians);

    landing.yawAligned = ...
        abs(landing.yawErrorRadians) <= ...
        config.landing.yawTolerance;

    landing.touchdownTimer = 0;
    landing.descentRateCommand = 0;

    landing.contactDetected = ...
        drone.touchdownDetected;

    landing.contactVerified = ...
        drone.touchdownVerified;

    %% Initialize landing timing
    if isnan(drone.landingStartTime)

        drone.landingStartTime = ...
            simulationTime;

        drone.landingPhaseStartTime = ...
            simulationTime;
    end

    %% Landing state machine
    switch drone.missionState

        case "LANDING_APPROACH"

            drone.landingPhase = ...
                "APPROACH";

            targetPosition = [
                goal(1), ...
                goal(2), ...
                config.landing.approachAltitude
            ];

            positionError = ...
                targetPosition - drone.position;

            horizontalError = ...
                norm(positionError(1:2));

            verticalError = ...
                abs(positionError(3));

            yawError = ...
                wrapAngleToPiLocal( ...
                    landingYaw - drone.yaw);

            yawAligned = ...
                abs(yawError) <= ...
                config.landing.yawTolerance;

            %% Position command
            commandVelocity = ...
                config.landing.positionGain * ...
                positionError;

            commandVelocity(1:2) = ...
                limitVectorMagnitude( ...
                    commandVelocity(1:2), ...
                    config.landing.approachHorizontalSpeed);

            commandVelocity(3) = max( ...
                -config.landing.descentSpeed, ...
                min( ...
                    config.landing.descentSpeed, ...
                    commandVelocity(3)));

            %% Yaw stability timer
            if yawAligned

                if isnan(drone.yawAlignedStartTime)

                    drone.yawAlignedStartTime = ...
                        simulationTime;
                end

            else

                drone.yawAlignedStartTime = NaN;
            end

            if isnan(drone.yawAlignedStartTime)

                yawStableDuration = 0;

            else

                yawStableDuration = ...
                    simulationTime - ...
                    drone.yawAlignedStartTime;
            end

            positionAligned = ...
                horizontalError <= ...
                config.landing.approachHorizontalTolerance && ...
                verticalError <= ...
                config.landing.approachVerticalTolerance;

            yawStablyAligned = ...
                yawAligned && ...
                yawStableDuration >= ...
                config.landing.yawStabilityTime;

            %% Begin descent only after position and yaw are stable
            if positionAligned && yawStablyAligned

                drone.missionState = ...
                    "LANDING_DESCENT";

                drone.landingPhase = ...
                    "DESCENT";

                drone.landingPhaseStartTime = ...
                    simulationTime;

                drone.yawAlignedStartTime = NaN;

                fprintf( ...
                    ['Landing position and yaw aligned. ' ...
                     'Beginning controlled descent.\n']);
            end

        case "LANDING_DESCENT"

            drone.landingPhase = ...
                "DESCENT";

            targetPosition = [
                goal(1), ...
                goal(2), ...
                config.landing.flareAltitude
            ];

            horizontalErrorVector = ...
                goal(1:2) - ...
                drone.position(1:2);

            horizontalError = ...
                norm(horizontalErrorVector);

            verticalError = ...
                drone.position(3) - ...
                config.landing.flareAltitude;

            horizontalCommand = ...
                config.landing.positionGain * ...
                horizontalErrorVector;

            horizontalCommand = ...
                limitVectorMagnitude( ...
                    horizontalCommand, ...
                    config.landing.descentHorizontalSpeed);

            commandVelocity = [
                horizontalCommand, ...
                -config.landing.descentSpeed
            ];

            if drone.position(3) <= ...
                    config.landing.flareAltitude

                commandVelocity(3) = 0;
            end

            yawError = ...
                wrapAngleToPiLocal( ...
                    landingYaw - drone.yaw);

            yawAligned = ...
                abs(yawError) <= ...
                config.landing.yawTolerance;

            if drone.position(3) <= ...
                    config.landing.flareAltitude + ...
                    config.landing.flareVerticalTolerance && ...
                    horizontalError <= ...
                    config.landing.descentHorizontalTolerance && ...
                    yawAligned

                drone.missionState = ...
                    "LANDING_FLARE";

                drone.landingPhase = ...
                    "FLARE";

                drone.landingPhaseStartTime = ...
                    simulationTime;

                fprintf( ...
                    'Flare altitude reached. Beginning final flare.\n');
            end

        case "LANDING_FLARE"

            drone.landingPhase = ...
                "FLARE";

            targetPosition = [
                goal(1), ...
                goal(2), ...
                config.landing.touchdownHeight
            ];

            horizontalErrorVector = ...
                goal(1:2) - ...
                drone.position(1:2);

            horizontalError = ...
                norm(horizontalErrorVector);

            verticalError = ...
                drone.position(3) - ...
                config.landing.touchdownHeight;

            horizontalCommand = ...
                config.landing.positionGain * ...
                horizontalErrorVector;

            horizontalCommand = ...
                limitVectorMagnitude( ...
                    horizontalCommand, ...
                    config.landing.flareHorizontalSpeed);

            verticalCommand = ...
                config.landing.positionGain * ...
                ( ...
                    config.landing.touchdownHeight - ...
                    drone.position(3));

            verticalCommand = max( ...
                -config.landing.flareDescentSpeed, ...
                min(0, verticalCommand));

            commandVelocity = [
                horizontalCommand, ...
                verticalCommand
            ];

            yawError = ...
                wrapAngleToPiLocal( ...
                    landingYaw - drone.yaw);

            yawAligned = ...
                abs(yawError) <= ...
                config.landing.yawTolerance;

            horizontalContactValid = ...
                horizontalError <= ...
                config.landing.touchdownHorizontalTolerance;

            verticalContactValid = ...
                drone.position(3) <= ...
                config.landing.touchdownHeight + ...
                config.landing.touchdownVerticalTolerance;

            verticalSpeedValid = ...
                abs(drone.velocity(3)) <= ...
                config.landing.maximumTouchdownVerticalSpeed;

            totalSpeedValid = ...
                norm(drone.velocity) <= ...
                config.landing.maximumTouchdownSpeed;

            if horizontalContactValid && ...
                    verticalContactValid && ...
                    verticalSpeedValid && ...
                    totalSpeedValid && ...
                    yawAligned

                drone.touchdownDetected = true;

                drone.touchdownStartTime = ...
                    simulationTime;

                drone.touchdownPosition = ...
                    drone.position;

                drone.touchdownSpeed = ...
                    norm(drone.velocity);

                drone.touchdownVerticalSpeed = ...
                    abs(drone.velocity(3));

                drone.missionState = ...
                    "TOUCHDOWN_VERIFY";

                drone.landingPhase = ...
                    "TOUCHDOWN_VERIFY";

                drone.landingPhaseStartTime = ...
                    simulationTime;

                fprintf( ...
                    ['Touchdown detected with landing yaw aligned. ' ...
                     'Verifying stable ground contact.\n']);
            end

        case "TOUCHDOWN_VERIFY"

            drone.landingPhase = ...
                "TOUCHDOWN_VERIFY";

            drone.groundLockActive = true;
            drone.yawControlActive = true;

            drone.commandedYaw = ...
                landingYaw;

            targetPosition = ...
                goal;

            commandVelocity = ...
                [0, 0, 0];

            %% Apply physical ground lock
            drone.position = ...
                goal;

            drone.previousPosition = ...
                goal;

            drone.airVelocity = ...
                [0, 0, 0];

            drone.windVelocity = ...
                [0, 0, 0];

            drone.velocity = ...
                [0, 0, 0];

            drone.acceleration = ...
                [0, 0, 0];

            drone.roll = 0;
            drone.pitch = 0;

            drone.yaw = ...
                landingYaw;

            drone.yawError = 0;
            drone.commandedYawRate = 0;

            if isnan(drone.touchdownStartTime)

                drone.touchdownStartTime = ...
                    simulationTime;
            end

            touchdownTimer = ...
                simulationTime - ...
                drone.touchdownStartTime;

            if touchdownTimer >= ...
                    config.landing.touchdownVerificationTime

                drone.touchdownVerified = true;

                drone.missionState = ...
                    "COMPLETE";

                drone.missionComplete = true;

                drone.landingPhase = ...
                    "COMPLETE";

                fprintf( ...
                    ['Touchdown verified. Final yaw locked at ' ...
                     '%.1f degrees.\n'], ...
                    rad2deg(landingYaw));

                fprintf( ...
                    'Landing complete.\n');
            end

        case "COMPLETE"

            drone.landingPhase = ...
                "COMPLETE";

            drone.groundLockActive = true;
            drone.missionComplete = true;

            drone.yawControlActive = true;

            drone.commandedYaw = ...
                landingYaw;

            targetPosition = ...
                goal;

            commandVelocity = ...
                [0, 0, 0];

            drone.position = ...
                goal;

            drone.previousPosition = ...
                goal;

            drone.airVelocity = ...
                [0, 0, 0];

            drone.windVelocity = ...
                [0, 0, 0];

            drone.velocity = ...
                [0, 0, 0];

            drone.acceleration = ...
                [0, 0, 0];

            drone.roll = 0;
            drone.pitch = 0;

            drone.yaw = ...
                landingYaw;

            drone.yawError = 0;
            drone.commandedYawRate = 0;

        otherwise

            targetPosition = ...
                goal;

            commandVelocity = ...
                [0, 0, 0];
    end

    %% Update landing diagnostics
    landing.phase = ...
        string(drone.landingPhase);

    landing.horizontalError = ...
        norm( ...
            goal(1:2) - ...
            drone.position(1:2));

    landing.verticalError = ...
        abs( ...
            drone.position(3) - ...
            goal(3));

    landing.descentRateCommand = ...
        commandVelocity(3);

    landing.groundLockActive = ...
        drone.groundLockActive;

    landing.contactDetected = ...
        drone.touchdownDetected;

    landing.contactVerified = ...
        drone.touchdownVerified;

    landing.yawErrorRadians = ...
        wrapAngleToPiLocal( ...
            landingYaw - drone.yaw);

    landing.yawErrorDegrees = ...
        rad2deg(landing.yawErrorRadians);

    landing.yawAligned = ...
        abs(landing.yawErrorRadians) <= ...
        config.landing.yawTolerance;

    if ~isnan(drone.touchdownStartTime)

        landing.touchdownTimer = max( ...
            0, ...
            simulationTime - ...
            drone.touchdownStartTime);

    else

        landing.touchdownTimer = 0;
    end
end


function limitedVector = ...
    limitVectorMagnitude(inputVector, maximumMagnitude)
%LIMITVECTORMAGNITUDE Limit a vector to the requested magnitude.

    vectorMagnitude = ...
        norm(inputVector);

    if vectorMagnitude > maximumMagnitude && ...
            vectorMagnitude > 1e-9

        limitedVector = ...
            inputVector / ...
            vectorMagnitude * ...
            maximumMagnitude;

    else

        limitedVector = ...
            inputVector;
    end
end


function wrappedAngle = wrapAngleToPiLocal(inputAngle)
%WRAPANGLETOPILOCAL Wrap an angle into the interval [-pi, pi].

    wrappedAngle = ...
        mod(inputAngle + pi, 2*pi) - pi;
end