function graphics = initializeMappingGraphics( ...
    mainFigure, occupancyGrid)
%INITIALIZEMAPPINGGRAPHICS Create the live occupancy-map display.

    %% Create map axes
    graphics.axes = axes( ...
        "Parent", mainFigure, ...
        "Position", [0.825, 0.07, 0.155, 0.37], ...
        "Color", [0.08, 0.09, 0.11]);

    hold(graphics.axes, "on");
    box(graphics.axes, "on");

    %% Initial unknown probability image
    initialProbability = ...
        0.5 * ones(size(occupancyGrid.logOdds));

    graphics.image = imagesc( ...
        graphics.axes, ...
        occupancyGrid.xCenters, ...
        occupancyGrid.yCenters, ...
        initialProbability);

    set( ...
        graphics.axes, ...
        "YDir", "normal");

    axis(graphics.axes, "equal");
    axis(graphics.axes, "tight");

    xlim( ...
        graphics.axes, ...
        occupancyGrid.xLimits);

    ylim( ...
        graphics.axes, ...
        occupancyGrid.yLimits);

    graphics.axes.XColor = [0.90, 0.90, 0.90];
    graphics.axes.YColor = [0.90, 0.90, 0.90];

    graphics.axes.FontSize = 8;

    xlabel( ...
        graphics.axes, ...
        "World X (m)");

    ylabel( ...
        graphics.axes, ...
        "World Y (m)");

    title( ...
        graphics.axes, ...
        "LIVE OCCUPANCY MAP", ...
        "Color", [0.90, 0.95, 1.00], ...
        "FontWeight", "bold", ...
        "FontSize", 9);

    %% Probability color map
    %
    % Low probability    = free, light
    % Probability 0.5    = unknown, grey
    % High probability   = occupied, dark
    mapColorCount = 256;

    freeToUnknown = [
        linspace(0.95, 0.45, mapColorCount/2)', ...
        linspace(0.95, 0.45, mapColorCount/2)', ...
        linspace(0.98, 0.50, mapColorCount/2)'
    ];

    unknownToOccupied = [
        linspace(0.45, 0.06, mapColorCount/2)', ...
        linspace(0.45, 0.06, mapColorCount/2)', ...
        linspace(0.50, 0.08, mapColorCount/2)'
    ];

    occupancyColorMap = [
        freeToUnknown
        unknownToOccupied
    ];

    colormap( ...
        graphics.axes, ...
        occupancyColorMap);

    clim( ...
        graphics.axes, ...
        [0, 1]);

    %% Planned route
    graphics.plannedRoute = plot( ...
        graphics.axes, ...
        NaN, ...
        NaN, ...
        "--", ...
        "Color", [0.10, 0.65, 0.90], ...
        "LineWidth", 1.0);

    %% Actual drone path
    graphics.droneTrail = animatedline( ...
        graphics.axes, ...
        "Color", [0.10, 0.90, 1.00], ...
        "LineWidth", 1.5, ...
        "MaximumNumPoints", 5000);

    %% Drone marker
    graphics.droneMarker = plot( ...
        graphics.axes, ...
        NaN, ...
        NaN, ...
        "^", ...
        "MarkerSize", 7, ...
        "MarkerFaceColor", [0.20, 1.00, 0.30], ...
        "MarkerEdgeColor", "black");

    %% Dynamic bird marker
    graphics.birdMarker = plot( ...
        graphics.axes, ...
        NaN, ...
        NaN, ...
        "o", ...
        "MarkerSize", 6, ...
        "MarkerFaceColor", [1.00, 0.55, 0.10], ...
        "MarkerEdgeColor", "black", ...
        "Visible", "off");

    %% Mapping statistics
    graphics.statisticsText = text( ...
        graphics.axes, ...
        occupancyGrid.xLimits(1) + 0.5, ...
        occupancyGrid.yLimits(2) - 0.6, ...
        "", ...
        "Color", [1.00, 0.85, 0.20], ...
        "FontName", "Consolas", ...
        "FontSize", 7, ...
        "VerticalAlignment", "top", ...
        "BackgroundColor", [0.08, 0.09, 0.11], ...
        "Margin", 2);
end