function updateMappingGraphics( ...
    graphics, occupancyGrid, drone, bird, config)
%UPDATEMAPPINGGRAPHICS Refresh the live occupancy map.

    %% Convert log-odds to occupancy probability
    probabilityMatrix = ...
        1 ./ (1 + exp(-occupancyGrid.logOdds));

    set( ...
        graphics.image, ...
        "CData", probabilityMatrix);

    %% Planned mission route
    set( ...
        graphics.plannedRoute, ...
        "XData", config.mission.waypoints(:,1), ...
        "YData", config.mission.waypoints(:,2));

    %% Actual drone path
    addpoints( ...
        graphics.droneTrail, ...
        drone.position(1), ...
        drone.position(2));

    %% Drone marker
    set( ...
        graphics.droneMarker, ...
        "XData", drone.position(1), ...
        "YData", drone.position(2));

    %% Bird marker
    if bird.active

        set( ...
            graphics.birdMarker, ...
            "XData", bird.position(1), ...
            "YData", bird.position(2), ...
            "Visible", "on");

    else

        set( ...
            graphics.birdMarker, ...
            "Visible", "off");
    end

    %% Statistics
    statisticsMessage = sprintf( ...
        [ ...
            'Coverage: %5.1f%%\n' ...
            'Free:     %5d\n' ...
            'Occupied: %5d\n' ...
            'Updates:  %5d' ...
        ], ...
        occupancyGrid.coveragePercent, ...
        occupancyGrid.freeCellCount, ...
        occupancyGrid.occupiedCellCount, ...
        occupancyGrid.updateCount);

    graphics.statisticsText.String = ...
        statisticsMessage;
end