function occupancyGrid = updateOccupancyMap( ...
    occupancyGrid, lidar, drone, simulationTime, config)
%UPDATEOCCUPANCYMAP Integrate one LiDAR scan into the map.
%
% For every LiDAR ray:
%
%   Cells between drone and endpoint → free observation
%
%   Static obstacle endpoint         → occupied observation
%
%   Dynamic bird endpoint            → not permanently occupied
%
% A log-odds representation allows repeated observations to gradually
% increase or decrease confidence.

    %% Respect the configured map-update interval
    timeSinceLastUpdate = ...
        simulationTime - occupancyGrid.lastUpdateTime;

    if timeSinceLastUpdate < ...
            config.mapping.updateInterval

        return;
    end

    occupancyGrid.lastUpdateTime = simulationTime;
    occupancyGrid.updateCount = ...
        occupancyGrid.updateCount + 1;

    rayOrigin = drone.position(1:2);

    numberOfRays = numel(lidar.ranges);

    %% Process every LiDAR ray
    for rayIndex = 1:numberOfRays

        rayDistance = lidar.ranges(rayIndex);

        rayDirection = [
            cos(lidar.worldAngles(rayIndex)), ...
            sin(lidar.worldAngles(rayIndex))
        ];

        rayEndpoint = ...
            rayOrigin + rayDistance * rayDirection;

        %% Determine sampling density
        numberOfSamples = max( ...
            2, ...
            ceil( ...
                rayDistance * ...
                occupancyGrid.resolution * ...
                config.mapping.samplesPerCell));

        sampleDistances = linspace( ...
            0, ...
            rayDistance, ...
            numberOfSamples);

        sampleX = ...
            rayOrigin(1) + ...
            sampleDistances * rayDirection(1);

        sampleY = ...
            rayOrigin(2) + ...
            sampleDistances * rayDirection(2);

        %% Convert ray samples to map cells
        [rowIndices, columnIndices, validMask] = ...
            worldToGridIndices( ...
                occupancyGrid, ...
                sampleX, ...
                sampleY);

        rowIndices = rowIndices(validMask);
        columnIndices = columnIndices(validMask);

        if isempty(rowIndices)
            continue;
        end

        linearIndices = sub2ind( ...
            size(occupancyGrid.logOdds), ...
            rowIndices, ...
            columnIndices);

        % Avoid repeatedly updating the same cell for one ray.
        linearIndices = unique( ...
            linearIndices, ...
            "stable");

        %% Determine whether the endpoint is occupied
        rayHitSomething = ...
            lidar.hitDetected(rayIndex);

        hitSource = ...
            lidar.hitSource(rayIndex);

        staticObstacleHit = ...
            rayHitSomething && hitSource == 1;

        dynamicObstacleHit = ...
            rayHitSomething && hitSource == 2;

        dynamicObstacleShouldBeMapped = ...
            dynamicObstacleHit && ...
            config.mapping.includeDynamicObstacles;

        endpointIsOccupied = ...
            staticObstacleHit || ...
            dynamicObstacleShouldBeMapped;

        %% Mark free cells
        if endpointIsOccupied && numel(linearIndices) >= 2

            freeIndices = ...
                linearIndices(1:end-1);

        else

            freeIndices = ...
                linearIndices;
        end

        if ~isempty(freeIndices)

            occupancyGrid.logOdds(freeIndices) = ...
                occupancyGrid.logOdds(freeIndices) + ...
                config.mapping.freeLogOddsIncrement;
        end

        %% Mark static obstacle endpoint occupied
        if endpointIsOccupied

            endpointIndex = ...
                linearIndices(end);

            occupancyGrid.logOdds(endpointIndex) = ...
                occupancyGrid.logOdds(endpointIndex) + ...
                config.mapping.occupiedLogOddsIncrement;
        end
    end

    %% Clamp map confidence
    occupancyGrid.logOdds = min( ...
        config.mapping.maximumLogOdds, ...
        max( ...
            config.mapping.minimumLogOdds, ...
            occupancyGrid.logOdds));

    %% Update mapping statistics
    probabilityMatrix = ...
        logOddsToProbability( ...
            occupancyGrid.logOdds);

    freeMask = ...
        probabilityMatrix < ...
        config.mapping.freeThreshold;

    occupiedMask = ...
        probabilityMatrix > ...
        config.mapping.occupiedThreshold;

    unknownMask = ...
        ~freeMask & ~occupiedMask;

    occupancyGrid.freeCellCount = ...
        nnz(freeMask);

    occupancyGrid.occupiedCellCount = ...
        nnz(occupiedMask);

    occupancyGrid.unknownCellCount = ...
        nnz(unknownMask);

    occupancyGrid.observedCellCount = ...
        occupancyGrid.freeCellCount + ...
        occupancyGrid.occupiedCellCount;

    occupancyGrid.coveragePercent = ...
        100 * occupancyGrid.observedCellCount / ...
        numel(probabilityMatrix);
end


function [rowIndices, columnIndices, validMask] = ...
    worldToGridIndices(occupancyGrid, worldX, worldY)
%WORLDTOGRIDINDICES Convert world coordinates into matrix indices.

    columnIndices = floor( ...
        (worldX - occupancyGrid.xLimits(1)) * ...
        occupancyGrid.resolution) + 1;

    rowIndices = floor( ...
        (worldY - occupancyGrid.yLimits(1)) * ...
        occupancyGrid.resolution) + 1;

    validMask = ...
        rowIndices >= 1 & ...
        rowIndices <= occupancyGrid.numberOfRows & ...
        columnIndices >= 1 & ...
        columnIndices <= occupancyGrid.numberOfColumns;

    rowIndices = round(rowIndices);
    columnIndices = round(columnIndices);
end


function probabilityMatrix = ...
    logOddsToProbability(logOddsMatrix)
%LOGODDSTOPROBABILITY Convert log-odds values to probabilities.

    probabilityMatrix = ...
        1 ./ (1 + exp(-logOddsMatrix));
end