function graphics = drawBird(ax, bird)
%DRAWBIRD Create a simplified three-dimensional bird model.

    graphics.transform = hgtransform( ...
        "Parent", ax);

    %% Bird body
    [bodyX, bodyY, bodyZ] = sphere(16);

    graphics.body = surf( ...
        bodyX * 0.38, ...
        bodyY * 0.18, ...
        bodyZ * 0.16, ...
        "Parent", graphics.transform, ...
        "FaceColor", [0.28, 0.24, 0.20], ...
        "EdgeColor", "none");

    %% Head
    [headX, headY, headZ] = sphere(12);

    graphics.head = surf( ...
        headX * 0.15 + 0.36, ...
        headY * 0.13, ...
        headZ * 0.13 + 0.03, ...
        "Parent", graphics.transform, ...
        "FaceColor", [0.34, 0.30, 0.25], ...
        "EdgeColor", "none");

    %% Beak
    graphics.beak = patch( ...
        "Parent", graphics.transform, ...
        "XData", [0.48, 0.72, 0.48], ...
        "YData", [-0.07, 0, 0.07], ...
        "ZData", [0.04, 0.02, 0.04], ...
        "FaceColor", [0.95, 0.55, 0.10], ...
        "EdgeColor", "none");

    %% Left wing
    graphics.leftWing = patch( ...
        "Parent", graphics.transform, ...
        "XData", [0.15, -0.15, -0.38, 0.05], ...
        "YData", [0.08, 0.35, 0.75, 0.18], ...
        "ZData", [0, 0.02, 0, -0.02], ...
        "FaceColor", [0.42, 0.36, 0.29], ...
        "EdgeColor", [0.12, 0.10, 0.08]);

    %% Right wing
    graphics.rightWing = patch( ...
        "Parent", graphics.transform, ...
        "XData", [0.15, -0.15, -0.38, 0.05], ...
        "YData", [-0.08, -0.35, -0.75, -0.18], ...
        "ZData", [0, 0.02, 0, -0.02], ...
        "FaceColor", [0.42, 0.36, 0.29], ...
        "EdgeColor", [0.12, 0.10, 0.08]);

    %% Tail
    graphics.tail = patch( ...
        "Parent", graphics.transform, ...
        "XData", [-0.32, -0.65, -0.55], ...
        "YData", [0, 0.20, -0.20], ...
        "ZData", [0, -0.02, -0.02], ...
        "FaceColor", [0.30, 0.25, 0.20], ...
        "EdgeColor", "none");

    %% Dynamic-obstacle label
    graphics.label = text( ...
        ax, ...
        bird.position(1), ...
        bird.position(2), ...
        bird.position(3) + 0.60, ...
        "DYNAMIC BIRD", ...
        "Color", [1.00, 0.60, 0.15], ...
        "FontWeight", "bold", ...
        "FontSize", 8, ...
        "HorizontalAlignment", "center", ...
        "Visible", "off");

    graphics.transform.Matrix = ...
        makehgtform("translate", bird.position) * ...
        makehgtform("zrotate", bird.yaw);

    graphics.transform.Visible = "off";
end