%% Autonomous Drone Navigation Project
% Stage 10:
% Portfolio-ready multi-sensor autonomous UAV dashboard with
% refined landing, dedicated telemetry cards, logging, video,
% and automatic post-mission performance plots.

clc;
clear;
close all;

%% Add project folders
projectRoot = fileparts(mfilename("fullpath"));
addpath(genpath(projectRoot));

fprintf("Autonomous Drone Navigation Project\n");
fprintf("Project root: %s\n", projectRoot);
fprintf("All project folders added to the MATLAB path.\n");

%% Load configuration
config = simulationConfig();
config.projectRoot = projectRoot;

%% Initialize simulation states
drone = initializeDrone(config);
bird = initializeBird(config);
wind = initializeWind(config);

occupancyGrid = initializeOccupancyMap(config);

%% Create figure
mainFigure = figure( ...
    "Name", "Autonomous Drone Navigation", ...
    "NumberTitle", "off", ...
    "Color", [0.08, 0.09, 0.11], ...
    "Position", [20, 20, 1700, 960]);

%% Main 3D axes
mainAxes = axes( ...
    "Parent", mainFigure, ...
    "Position", [0.02, 0.07, 0.60, 0.87], ...
    "Color", [0.06, 0.07, 0.08]);

hold(mainAxes, "on");

environment = createUrbanEnvironment( ...
    mainAxes, ...
    config);

mainAxes.Color = [0.06, 0.07, 0.08];

mainAxes.XColor = [0.90, 0.90, 0.90];
mainAxes.YColor = [0.90, 0.90, 0.90];
mainAxes.ZColor = [0.90, 0.90, 0.90];

mainAxes.GridColor = [0.50, 0.50, 0.50];
mainAxes.GridAlpha = 0.30;

axis(mainAxes, "vis3d");

title( ...
    mainAxes, ...
    "Autonomous UAV Multi-Sensor Mission");

%% Draw drone and bird
droneGraphics = drawDrone( ...
    mainAxes, ...
    drone, ...
    config);

birdGraphics = drawBird( ...
    mainAxes, ...
    bird);

%% Flight trail
flightTrail = animatedline( ...
    mainAxes, ...
    "Color", [0.10, 0.90, 1.00], ...
    "LineWidth", 2.0, ...
    "MaximumNumPoints", 5000);

%% Active target marker
targetMarker = plot3( ...
    mainAxes, ...
    NaN, ...
    NaN, ...
    NaN, ...
    "p", ...
    "MarkerSize", 14, ...
    "MarkerFaceColor", [1.00, 0.80, 0.10], ...
    "MarkerEdgeColor", "black");

%% Landing vertical guide
landingGuide = plot3( ...
    mainAxes, ...
    [config.mission.goalPosition(1), ...
     config.mission.goalPosition(1)], ...
    [config.mission.goalPosition(2), ...
     config.mission.goalPosition(2)], ...
    [0, config.landing.approachAltitude], ...
    ":", ...
    "Color", [0.20, 1.00, 0.45], ...
    "LineWidth", 1.4);

%% Controller arrows
nominalVelocityArrow = quiver3( ...
    mainAxes, 0, 0, 0, 0, 0, 0, 0, ...
    "Color", [0.20, 1.00, 0.30], ...
    "LineWidth", 2.0);

avoidanceVelocityArrow = quiver3( ...
    mainAxes, 0, 0, 0, 0, 0, 0, 0, ...
    "Color", [1.00, 0.30, 0.10], ...
    "LineWidth", 2.0);

commandVelocityArrow = quiver3( ...
    mainAxes, 0, 0, 0, 0, 0, 0, 0, ...
    "Color", [1.00, 0.85, 0.10], ...
    "LineWidth", 2.2);

windVelocityArrow = quiver3( ...
    mainAxes, 0, 0, 0, 0, 0, 0, 0, ...
    "Color", [0.65, 0.35, 1.00], ...
    "LineWidth", 2.5);

windCompensationArrow = quiver3( ...
    mainAxes, 0, 0, 0, 0, 0, 0, 0, ...
    "Color", [0.20, 0.90, 1.00], ...
    "LineWidth", 2.2, ...
    "LineStyle", "--");

%% Mission status banner
statusText = annotation( ...
    mainFigure, ...
    "textbox", ...
    [0.64, 0.925, 0.34, 0.045], ...
    "String", "MISSION INITIALIZING", ...
    "Color", [1.00, 0.85, 0.15], ...
    "BackgroundColor", [0.12, 0.14, 0.17], ...
    "EdgeColor", [0.35, 0.40, 0.48], ...
    "LineWidth", 1.1, ...
    "FontWeight", "bold", ...
    "FontSize", 12, ...
    "HorizontalAlignment", "center", ...
    "VerticalAlignment", "middle");

%% Stage 10 dashboard cards
flightText = createDashboardCard( ...
    mainFigure, ...
    [0.64, 0.805, 0.165, 0.105], ...
    "FLIGHT TELEMETRY");

landingText = createDashboardCard( ...
    mainFigure, ...
    [0.815, 0.805, 0.165, 0.105], ...
    "LANDING SYSTEM");

birdText = createDashboardCard( ...
    mainFigure, ...
    [0.64, 0.685, 0.165, 0.105], ...
    "DYNAMIC BIRD / APF");

systemText = createDashboardCard( ...
    mainFigure, ...
    [0.815, 0.685, 0.165, 0.105], ...
    "MISSION SYSTEMS");

%% Initialize displays
fpvGraphics = initializeFPVGraphics( ...
    mainFigure, ...
    config);

fpvGraphics.axes.Position = ...
    [0.64, 0.395, 0.34, 0.255];

lidarGraphics = initializeLidarGraphics( ...
    mainAxes, ...
    mainFigure, ...
    config);

lidarGraphics.topAxes.Position = ...
    [0.64, 0.065, 0.16, 0.25];

title( ...
    lidarGraphics.topAxes, ...
    "LIVE 360° LIDAR", ...
    "Color", [0.90, 0.95, 1.00], ...
    "FontWeight", "bold", ...
    "FontSize", 9);

mappingGraphics = initializeMappingGraphics( ...
    mainFigure, ...
    occupancyGrid);

mappingGraphics.axes.Position = ...
    [0.82, 0.065, 0.16, 0.25];

drawnow;

%% Initialize recorder
recorder = initializeMissionRecorder(config);

%% Simulation variables
simulationTime = 0;

waypoints = config.mission.waypoints;
numberOfWaypoints = size(waypoints, 1);

avoidanceActivationCount = 0;
birdAvoidanceActivationCount = 0;

minimumBirdClearance = Inf;

maximumLateralDeviation = 0;
cumulativeLateralDeviation = 0;
lateralDeviationSamples = 0;
averageLateralDeviation = 0;

fpvBirdVisibleSteps = 0;

landingDuration = NaN;
maximumLandingDescentSpeed = 0;
touchdownVerificationDuration = 0;

missionError = [];

landing.phase = "NOT_STARTED";
landing.groundLockActive = false;
landing.horizontalError = Inf;
landing.verticalError = Inf;
landing.touchdownTimer = 0;
landing.descentRateCommand = 0;
landing.contactDetected = false;
landing.contactVerified = false;

fprintf("Starting autonomous mission...\n");
fprintf("FPV camera enabled.\n");
fprintf("Refined autonomous landing enabled.\n");

if config.wind.enabled

    fprintf("Wind disturbance enabled.\n");

    fprintf( ...
        "Mean wind velocity: [%.2f, %.2f, %.2f] m/s\n", ...
        config.wind.meanVelocity(1), ...
        config.wind.meanVelocity(2), ...
        config.wind.meanVelocity(3));

    if config.wind.compensationEnabled

        fprintf( ...
            "Wind compensation enabled with gain %.2f.\n", ...
            config.wind.compensationGain);
    end
end

try

    %% Main simulation loop
    while simulationTime <= config.maxSimulationTime && ...
            isvalid(mainFigure) && ...
            ~drone.missionComplete

        %% Update wind and bird
        wind = updateWind( ...
            wind, ...
            simulationTime, ...
            config);

        bird = updateBird( ...
            bird, ...
            simulationTime, ...
            config);

        updateBirdGraphics( ...
            birdGraphics, ...
            bird);

        %% Sensor scan before control
        lidar = simulateLidar( ...
            drone, ...
            environment, ...
            bird, ...
            config);

        occupancyGrid = updateOccupancyMap( ...
            occupancyGrid, ...
            lidar, ...
            drone, ...
            simulationTime, ...
            config);

        %% Default control diagnostics
        avoidance.active = false;
        avoidance.emergencyActive = false;

        avoidance.repulsiveVelocity = [0, 0, 0];
        avoidance.tangentialVelocity = [0, 0, 0];
        avoidance.totalAvoidanceVelocity = [0, 0, 0];

        avoidance.nearestObstacleDistance = Inf;
        avoidance.obstacleCount = 0;

        nominalVelocity = [0, 0, 0];
        commandVelocity = [0, 0, 0];

        landing.phase = string(drone.landingPhase);
        landing.groundLockActive = drone.groundLockActive;
        landing.horizontalError = Inf;
        landing.verticalError = Inf;
        landing.touchdownTimer = 0;
        landing.descentRateCommand = 0;
        landing.contactDetected = drone.touchdownDetected;
        landing.contactVerified = drone.touchdownVerified;

        %% Mission state machine
        switch drone.missionState

            case "TAKEOFF"

                targetPosition = [
                    config.drone.startPosition(1), ...
                    config.drone.startPosition(2), ...
                    config.drone.takeoffAltitude
                ];

                nominalVelocity = waypointController( ...
                    drone.position, ...
                    targetPosition, ...
                    config);

                commandVelocity = nominalVelocity;

                if norm(targetPosition - drone.position) < ...
                        config.mission.waypointTolerance

                    drone.currentWaypointIndex = 2;
                    drone.missionState = "NAVIGATION";

                    fprintf("Takeoff complete.\n");
                end

            case "NAVIGATION"

                targetPosition = ...
                    waypoints( ...
                        drone.currentWaypointIndex, :);

                nominalVelocity = waypointController( ...
                    drone.position, ...
                    targetPosition, ...
                    config);

                [commandVelocity, avoidance] = ...
                    potentialFieldController( ...
                        nominalVelocity, ...
                        lidar, ...
                        drone, ...
                        config);

                if norm(targetPosition - drone.position) < ...
                        config.mission.waypointTolerance

                    fprintf( ...
                        "Waypoint %d reached.\n", ...
                        drone.currentWaypointIndex);

                    if drone.currentWaypointIndex < ...
                            numberOfWaypoints

                        drone.currentWaypointIndex = ...
                            drone.currentWaypointIndex + 1;

                    else

                        drone.missionState = ...
                            "LANDING_APPROACH";

                        drone.landingPhase = ...
                            "APPROACH";

                        drone.landingStartTime = ...
                            simulationTime;

                        drone.landingPhaseStartTime = ...
                            simulationTime;

                        fprintf( ...
                            "Beginning refined autonomous landing.\n");
                    end
                end

            case { ...
                    "LANDING_APPROACH", ...
                    "LANDING_DESCENT", ...
                    "LANDING_FLARE", ...
                    "TOUCHDOWN_VERIFY", ...
                    "COMPLETE" ...
                    }

                [ ...
                    commandVelocity, ...
                    targetPosition, ...
                    drone, ...
                    landing ...
                ] = refinedLandingController( ...
                    drone, ...
                    simulationTime, ...
                    config);

                nominalVelocity = commandVelocity;

            otherwise

                targetPosition = drone.position;
                nominalVelocity = [0, 0, 0];
                commandVelocity = [0, 0, 0];
        end

        %% Avoidance statistics
        birdDetectionCount = ...
            sum(lidar.hitSource == 2);

        if avoidance.active

            avoidanceActivationCount = ...
                avoidanceActivationCount + 1;

            if birdDetectionCount > 0

                birdAvoidanceActivationCount = ...
                    birdAvoidanceActivationCount + 1;
            end
        end

        %% Bird clearance
        if bird.active

            currentBirdClearance = ...
                norm(drone.position - bird.position) - ...
                drone.radius - bird.radius;

            minimumBirdClearance = min( ...
                minimumBirdClearance, ...
                currentBirdClearance);
        end

        %% Update dynamics unless touchdown ground lock is active
        if ~landing.groundLockActive && ...
                ~drone.missionComplete

            drone = updateDroneDynamics( ...
                drone, ...
                commandVelocity, ...
                wind, ...
                config);

        else

            drone.position = ...
                config.mission.goalPosition;

            drone.previousPosition = ...
                config.mission.goalPosition;

            drone.airVelocity = [0, 0, 0];
            drone.windVelocity = [0, 0, 0];
            drone.velocity = [0, 0, 0];
            drone.acceleration = [0, 0, 0];

            drone.roll = 0;
            drone.pitch = 0;
        end

        %% Landing statistics
        if startsWith( ...
                string(drone.missionState), ...
                "LANDING") || ...
                drone.missionState == "TOUCHDOWN_VERIFY"

            maximumLandingDescentSpeed = max( ...
                maximumLandingDescentSpeed, ...
                max(0, -drone.velocity(3)));
        end

        if drone.missionState == "TOUCHDOWN_VERIFY"

            touchdownVerificationDuration = ...
                landing.touchdownTimer;
        end

        %% Route deviation statistics
        if drone.missionState == "NAVIGATION"

            currentLateralDeviation = ...
                abs(drone.position(2));

            maximumLateralDeviation = max( ...
                maximumLateralDeviation, ...
                currentLateralDeviation);

            cumulativeLateralDeviation = ...
                cumulativeLateralDeviation + ...
                currentLateralDeviation;

            lateralDeviationSamples = ...
                lateralDeviationSamples + 1;

            averageLateralDeviation = ...
                cumulativeLateralDeviation / ...
                lateralDeviationSamples;
        end

        %% Updated sensor scan
        lidar = simulateLidar( ...
            drone, ...
            environment, ...
            bird, ...
            config);

        %% Update visualizations
        updateDroneGraphics( ...
            droneGraphics, ...
            drone);

        updateLidarGraphics( ...
            lidarGraphics, ...
            lidar, ...
            drone);

        updateMappingGraphics( ...
            mappingGraphics, ...
            occupancyGrid, ...
            drone, ...
            bird, ...
            config);

        fpv = updateFPVGraphics( ...
            fpvGraphics, ...
            drone, ...
            targetPosition, ...
            environment, ...
            bird, ...
            lidar, ...
            config);

        if fpv.birdVisible

            fpvBirdVisibleSteps = ...
                fpvBirdVisibleSteps + 1;
        end

        %% Flight trail
        addpoints( ...
            flightTrail, ...
            drone.position(1), ...
            drone.position(2), ...
            drone.position(3));

        %% Active target
        set( ...
            targetMarker, ...
            "XData", targetPosition(1), ...
            "YData", targetPosition(2), ...
            "ZData", targetPosition(3));

        %% Navigation vectors
        arrowScale = 1.2;

        set( ...
            nominalVelocityArrow, ...
            "XData", drone.position(1), ...
            "YData", drone.position(2), ...
            "ZData", drone.position(3), ...
            "UData", nominalVelocity(1) * arrowScale, ...
            "VData", nominalVelocity(2) * arrowScale, ...
            "WData", nominalVelocity(3) * arrowScale);

        set( ...
            avoidanceVelocityArrow, ...
            "XData", drone.position(1), ...
            "YData", drone.position(2), ...
            "ZData", drone.position(3), ...
            "UData", ...
            avoidance.totalAvoidanceVelocity(1) * arrowScale, ...
            "VData", ...
            avoidance.totalAvoidanceVelocity(2) * arrowScale, ...
            "WData", ...
            avoidance.totalAvoidanceVelocity(3) * arrowScale);

        set( ...
            commandVelocityArrow, ...
            "XData", drone.position(1), ...
            "YData", drone.position(2), ...
            "ZData", drone.position(3), ...
            "UData", commandVelocity(1) * arrowScale, ...
            "VData", commandVelocity(2) * arrowScale, ...
            "WData", commandVelocity(3) * arrowScale);

        %% Wind vectors
        set( ...
            windVelocityArrow, ...
            "XData", drone.position(1), ...
            "YData", drone.position(2), ...
            "ZData", drone.position(3) + 0.35, ...
            "UData", ...
            wind.totalVelocity(1) * config.wind.arrowScale, ...
            "VData", ...
            wind.totalVelocity(2) * config.wind.arrowScale, ...
            "WData", ...
            wind.totalVelocity(3) * config.wind.arrowScale);

        set( ...
            windCompensationArrow, ...
            "XData", drone.position(1), ...
            "YData", drone.position(2), ...
            "ZData", drone.position(3) + 0.20, ...
            "UData", ...
            wind.compensationVelocity(1) * ...
            config.wind.arrowScale, ...
            "VData", ...
            wind.compensationVelocity(2) * ...
            config.wind.arrowScale, ...
            "WData", ...
            wind.compensationVelocity(3) * ...
            config.wind.arrowScale);

        %% Telemetry calculations
        groundSpeed = norm(drone.velocity);
        airSpeed = norm(drone.airVelocity);

        birdDistance = ...
            norm(drone.position - bird.position);

        if bird.active
            birdStatus = "CROSSING";
        elseif bird.complete
            birdStatus = "COMPLETE";
        else
            birdStatus = "WAITING";
        end

        if avoidance.emergencyActive
            avoidanceStatus = "EMERGENCY";
        elseif avoidance.active && birdDetectionCount > 0
            avoidanceStatus = "BIRD ACTIVE";
        elseif avoidance.active
            avoidanceStatus = "STATIC ACTIVE";
        else
            avoidanceStatus = "CLEAR";
        end

        if isfinite(fpv.nearestForwardObstacle)

            fpvObstacleDistance = ...
                fpv.nearestForwardObstacle;

        else

            fpvObstacleDistance = ...
                config.fpv.maximumViewDistance;
        end

        %% Stage 10 dashboard-card content
        if bird.active
            currentBirdClearanceDisplay = ...
                birdDistance - drone.radius - bird.radius;
        else
            currentBirdClearanceDisplay = NaN;
        end

        if isfinite(minimumBirdClearance)
            minimumBirdClearanceDisplay = minimumBirdClearance;
        else
            minimumBirdClearanceDisplay = NaN;
        end

        flightText.String = sprintf( ...
            ['FLIGHT TELEMETRY\n' ...
             'Time:      %6.2f s\n' ...
             'State:     %-16s\n' ...
             'Waypoint:  %d / %d\n' ...
             'Position:  [%5.2f %5.2f %5.2f] m\n' ...
             'Ground/Air:%5.2f / %5.2f m/s\n' ...
             'Heading:   %6.1f deg'], ...
            simulationTime, ...
            char(drone.missionState), ...
            drone.currentWaypointIndex, ...
            numberOfWaypoints, ...
            drone.position(1), ...
            drone.position(2), ...
            drone.position(3), ...
            groundSpeed, ...
            airSpeed, ...
            mod(rad2deg(drone.yaw), 360));

        landingText.String = sprintf( ...
            ['LANDING SYSTEM\n' ...
             'Phase:      %-15s\n' ...
             'Ground lock:%-3s\n' ...
             'Horizontal: %5.2f m\n' ...
             'Vertical:   %5.2f m\n' ...
             'Descent cmd:%5.2f m/s\n' ...
             'TD timer:   %5.2f s'], ...
            char(landing.phase), ...
            yesNoText(landing.groundLockActive), ...
            landing.horizontalError, ...
            landing.verticalError, ...
            landing.descentRateCommand, ...
            landing.touchdownTimer);

        birdText.String = sprintf( ...
            ['DYNAMIC BIRD / APF\n' ...
             'Bird state: %-10s\n' ...
             'Position:   [%5.2f %5.2f %5.2f] m\n' ...
             'Distance:   %5.2f m\n' ...
             'Clearance:  %5.2f m (min %5.2f)\n' ...
             'LiDAR hits: %d   FPV: %-3s\n' ...
             'APF:        %-11s  steps %d'], ...
            char(birdStatus), ...
            bird.position(1), ...
            bird.position(2), ...
            bird.position(3), ...
            birdDistance, ...
            currentBirdClearanceDisplay, ...
            minimumBirdClearanceDisplay, ...
            birdDetectionCount, ...
            yesNoText(fpv.birdVisible), ...
            char(avoidanceStatus), ...
            birdAvoidanceActivationCount);

        systemText.String = sprintf( ...
            ['MISSION SYSTEMS\n' ...
             'Wind:      %5.2f m/s\n' ...
             'Map:       %5.1f %%\n' ...
             'Occupied:  %d cells\n' ...
             'FPV range: %5.2f m\n' ...
             'Log rows:  %d\n' ...
             'Video:     %d frames'], ...
            wind.speed, ...
            occupancyGrid.coveragePercent, ...
            occupancyGrid.occupiedCellCount, ...
            fpvObstacleDistance, ...
            recorder.loggedSampleCount, ...
            recorder.videoFrameCount);

        %% Status panel
        switch drone.missionState

            case "LANDING_APPROACH"

                statusText.String = ...
                    "LANDING: APPROACH AND ALIGNMENT";

                statusText.Color = ...
                    [0.20, 0.90, 1.00];

            case "LANDING_DESCENT"

                statusText.String = ...
                    "LANDING: CONTROLLED DESCENT";

                statusText.Color = ...
                    [0.30, 0.85, 1.00];

            case "LANDING_FLARE"

                statusText.String = ...
                    "LANDING: FINAL FLARE";

                statusText.Color = ...
                    [1.00, 0.80, 0.15];

            case "TOUCHDOWN_VERIFY"

                statusText.String = ...
                    "TOUCHDOWN: VERIFYING GROUND CONTACT";

                statusText.Color = ...
                    [1.00, 0.60, 0.10];

            otherwise

                if avoidance.emergencyActive

                    statusText.String = ...
                        "EMERGENCY COLLISION AVOIDANCE";

                    statusText.Color = ...
                        [1.00, 0.20, 0.10];

                elseif fpv.birdVisible && ...
                        birdDetectionCount > 0

                    statusText.String = ...
                        "FPV BIRD TRACKING AND AVOIDANCE";

                    statusText.Color = ...
                        [1.00, 0.60, 0.10];

                elseif avoidance.active

                    statusText.String = ...
                        "OBSTACLE AVOIDANCE ACTIVE";

                    statusText.Color = ...
                        [1.00, 0.78, 0.10];

                elseif wind.speed > 0.50

                    statusText.String = ...
                        "STRONG WIND COMPENSATION ACTIVE";

                    statusText.Color = ...
                        [0.65, 0.45, 1.00];

                else

                    statusText.String = ...
                        "MISSION STATE: " + ...
                        drone.missionState;

                    statusText.Color = ...
                        [0.20, 1.00, 0.35];
                end
        end

        %% Render and record
        drawnow;

        recorder = recordMissionStep( ...
            recorder, ...
            mainFigure, ...
            simulationTime, ...
            drone, ...
            bird, ...
            wind, ...
            avoidance, ...
            lidar, ...
            occupancyGrid, ...
            fpv, ...
            targetPosition, ...
            config);

        if config.realTimePlayback
            pause(config.timeStep);
        end

        simulationTime = ...
            simulationTime + config.timeStep;
    end

catch caughtError

    missionError = caughtError;

    warning( ...
        "AutonomousDroneMission:RuntimeError", ...
        "The mission stopped because of an error: %s", ...
        caughtError.message);
end

%% Final ground lock
if drone.missionComplete

    drone.position = ...
        config.mission.goalPosition;

    drone.previousPosition = ...
        config.mission.goalPosition;

    drone.airVelocity = [0, 0, 0];
    drone.windVelocity = [0, 0, 0];
    drone.velocity = [0, 0, 0];
    drone.acceleration = [0, 0, 0];

    drone.roll = 0;
    drone.pitch = 0;

    drone.groundLockActive = true;

    statusText.String = ...
        "MISSION COMPLETE — TOUCHDOWN VERIFIED";

    statusText.Color = ...
        [0.20, 1.00, 0.35];

    if isfinite(drone.landingStartTime)

        landingDuration = ...
            simulationTime - ...
            drone.landingStartTime;
    end

else

    statusText.String = ...
        "MISSION STOPPED";

    statusText.Color = ...
        [1.00, 0.35, 0.20];
end

drawnow;

%% Mission summary
summary.MissionCompleted = ...
    drone.missionComplete;

summary.SimulationTimeSeconds = ...
    simulationTime;

summary.DistanceTravelledMetres = ...
    drone.distanceTravelled;

summary.MaximumWindSpeedMetresPerSecond = ...
    wind.maximumSpeedObserved;

summary.AverageWindSpeedMetresPerSecond = ...
    wind.averageSpeed;

summary.MaximumLateralDeviationMetres = ...
    maximumLateralDeviation;

summary.AverageLateralDeviationMetres = ...
    averageLateralDeviation;

summary.TotalAPFActivationSteps = ...
    avoidanceActivationCount;

summary.BirdAvoidanceActivationSteps = ...
    birdAvoidanceActivationCount;

summary.MinimumBirdClearanceMetres = ...
    minimumBirdClearance;

summary.FPVBirdVisibleFrames = ...
    fpvBirdVisibleSteps;

summary.OccupancyCoveragePercent = ...
    occupancyGrid.coveragePercent;

summary.OccupancyMapUpdates = ...
    occupancyGrid.updateCount;

%% Finalize outputs
outputs = finalizeMissionRecorder( ...
    recorder, ...
    summary, ...
    config, ...
    drone, ...
    bird, ...
    wind, ...
    occupancyGrid);

%% Generate Stage 10 performance plots
plotOutputs = generateMissionReportPlots( ...
    outputs.telemetryFile, ...
    projectRoot);

%% Print results
if drone.missionComplete

    fprintf("\nMission completed successfully.\n");
    fprintf("Touchdown verified successfully.\n");

else

    fprintf("\nMission ended before completion.\n");
end

fprintf( ...
    "Total simulation time: %.2f seconds\n", ...
    simulationTime);

fprintf( ...
    "Distance travelled: %.2f meters\n", ...
    drone.distanceTravelled);

if isfinite(landingDuration)

    fprintf( ...
        "Total refined landing duration: %.2f seconds\n", ...
        landingDuration);
end

fprintf( ...
    "Maximum landing descent speed: %.2f m/s\n", ...
    maximumLandingDescentSpeed);

fprintf( ...
    "Touchdown verification duration: %.2f seconds\n", ...
    touchdownVerificationDuration);

if isfinite(drone.touchdownSpeed)

    fprintf( ...
        "Touchdown total speed: %.2f m/s\n", ...
        drone.touchdownSpeed);
end

if isfinite(drone.touchdownVerticalSpeed)

    fprintf( ...
        "Touchdown vertical speed: %.2f m/s\n", ...
        drone.touchdownVerticalSpeed);
end

fprintf( ...
    "Maximum wind speed: %.2f m/s\n", ...
    wind.maximumSpeedObserved);

fprintf( ...
    "Average wind speed: %.2f m/s\n", ...
    wind.averageSpeed);

fprintf( ...
    "Maximum lateral route deviation: %.2f meters\n", ...
    maximumLateralDeviation);

fprintf( ...
    "Average lateral route deviation: %.2f meters\n", ...
    averageLateralDeviation);

fprintf( ...
    "Total APF activation steps: %d\n", ...
    avoidanceActivationCount);

fprintf( ...
    "Bird avoidance activation steps: %d\n", ...
    birdAvoidanceActivationCount);

if isfinite(minimumBirdClearance)

    fprintf( ...
        "Minimum drone-to-bird clearance: %.2f meters\n", ...
        minimumBirdClearance);
end

fprintf( ...
    "FPV bird-visible frames: %d\n", ...
    fpvBirdVisibleSteps);

fprintf( ...
    "Occupancy-map coverage: %.1f percent\n", ...
    occupancyGrid.coveragePercent);

fprintf( ...
    "Occupancy-map updates: %d\n", ...
    occupancyGrid.updateCount);

fprintf( ...
    "Telemetry samples recorded: %d\n", ...
    recorder.loggedSampleCount);

fprintf( ...
    "Video frames recorded: %d\n", ...
    recorder.videoFrameCount);

fprintf("\nOutput files:\n");

if outputs.telemetrySaved
    fprintf("Telemetry CSV: %s\n", outputs.telemetryFile);
end

if outputs.summarySaved
    fprintf("Summary CSV:   %s\n", outputs.summaryFile);
end

if outputs.matSaved
    fprintf("MAT dataset:   %s\n", outputs.matFile);
end

if outputs.videoSaved
    fprintf("Mission video: %s\n", outputs.videoFile);
else
    fprintf("Mission video was not saved successfully.\n");
end

if plotOutputs.generated
    fprintf("Performance plots: %s\n", plotOutputs.outputDirectory);
else
    fprintf("Performance plots were not generated successfully.\n");
end

if ~isempty(missionError)
    rethrow(missionError);
end


function card = createDashboardCard(mainFigure, position, titleText)
%CREATEDASHBOARDCARD Create a bordered Stage 10 telemetry card.

    card = annotation( ...
        mainFigure, ...
        "textbox", ...
        position, ...
        "String", titleText, ...
        "Color", [0.90, 0.95, 1.00], ...
        "BackgroundColor", [0.12, 0.14, 0.17], ...
        "EdgeColor", [0.35, 0.40, 0.48], ...
        "LineWidth", 1.0, ...
        "FontName", "Consolas", ...
        "FontSize", 7.2, ...
        "Interpreter", "none", ...
        "FitBoxToText", "off", ...
        "VerticalAlignment", "top", ...
        "Margin", 7);
end


function outputText = yesNoText(logicalValue)
%YESNOTEXT Convert a logical value to compact text.

    if logicalValue
        outputText = "YES";
    else
        outputText = "NO";
    end
end