function reportOutputs = generateMissionReportPlots( ...
    telemetryInput, summaryInput, config, occupancyGrid)
%GENERATEMISSIONREPORTPLOTS Generate portfolio-quality mission reports.
%
% Stage 11 reporting upgrade
%
% Generated figures:
%
%   01_mission_trajectory_top_view.png
%   02_mission_trajectory_3d.png
%   03_flight_speed_and_wind.png
%   04_bird_encounter_and_apf.png
%   05_final_occupancy_map.png
%   06_mapping_progress.png
%   07_refined_landing_performance.png
%   08_mission_performance_summary.png
%
% The function uses mission data recorded by the simulation. It does not
% create artificial example trajectories or fabricated metrics.
%
% TELEMETRYINPUT may be:
%   - A MATLAB table
%   - A path to missionTelemetry.csv
%
% SUMMARYINPUT may be:
%   - A MATLAB table
%   - A summary structure
%   - A path to missionSummary.csv
%
% Example:
%
%   generateMissionReportPlots( ...
%       "output/data/missionTelemetry.csv", ...
%       "output/data/missionSummary.csv", ...
%       config, ...
%       occupancyGrid);

    %% Resolve project root
    if isfield(config, "projectRoot") && ...
            strlength(string(config.projectRoot)) > 0

        projectRoot = string(config.projectRoot);

    else

        currentFile = mfilename("fullpath");

        projectRoot = string( ...
            fileparts( ...
                fileparts(currentFile)));
    end

    %% Create output directory
    plotsDirectory = fullfile( ...
        projectRoot, ...
        "output", ...
        "plots");

    if ~isfolder(plotsDirectory)
        mkdir(plotsDirectory);
    end

    %% Load telemetry
    telemetryTable = loadTelemetryTable( ...
        telemetryInput);

    summaryData = loadSummaryData( ...
        summaryInput);

    %% Validate telemetry
    if isempty(telemetryTable) || ...
            height(telemetryTable) == 0

        error( ...
            "MissionReport:EmptyTelemetry", ...
            "No telemetry data is available for report generation.");
    end

    %% Normalize telemetry variable access
    time = getNumericColumn( ...
        telemetryTable, ...
        "TimeSeconds", ...
        height(telemetryTable), ...
        0);

    positionX = getNumericColumn( ...
        telemetryTable, ...
        "PositionXMetres", ...
        height(telemetryTable), ...
        NaN);

    positionY = getNumericColumn( ...
        telemetryTable, ...
        "PositionYMetres", ...
        height(telemetryTable), ...
        NaN);

    positionZ = getNumericColumn( ...
        telemetryTable, ...
        "PositionZMetres", ...
        height(telemetryTable), ...
        NaN);

    groundSpeed = getNumericColumn( ...
        telemetryTable, ...
        "GroundSpeedMetresPerSecond", ...
        height(telemetryTable), ...
        NaN);

    airSpeed = getNumericColumn( ...
        telemetryTable, ...
        "AirSpeedMetresPerSecond", ...
        height(telemetryTable), ...
        NaN);

    windSpeed = getNumericColumn( ...
        telemetryTable, ...
        "WindSpeedMetresPerSecond", ...
        height(telemetryTable), ...
        NaN);

    windX = getNumericColumn( ...
        telemetryTable, ...
        "WindXMetresPerSecond", ...
        height(telemetryTable), ...
        0);

    windY = getNumericColumn( ...
        telemetryTable, ...
        "WindYMetresPerSecond", ...
        height(telemetryTable), ...
        0);

    windZ = getNumericColumn( ...
        telemetryTable, ...
        "WindZMetresPerSecond", ...
        height(telemetryTable), ...
        0);

    groundVelocityZ = getNumericColumn( ...
        telemetryTable, ...
        "GroundVelocityZMetresPerSecond", ...
        height(telemetryTable), ...
        NaN);

    yawDegrees = getNumericColumn( ...
        telemetryTable, ...
        "YawDegrees", ...
        height(telemetryTable), ...
        NaN);

    targetDistance = getNumericColumn( ...
        telemetryTable, ...
        "TargetDistanceMetres", ...
        height(telemetryTable), ...
        NaN);

    distanceTravelled = getNumericColumn( ...
        telemetryTable, ...
        "DistanceTravelledMetres", ...
        height(telemetryTable), ...
        NaN);

    birdPositionX = getNumericColumn( ...
        telemetryTable, ...
        "BirdPositionXMetres", ...
        height(telemetryTable), ...
        NaN);

    birdPositionY = getNumericColumn( ...
        telemetryTable, ...
        "BirdPositionYMetres", ...
        height(telemetryTable), ...
        NaN);

    birdPositionZ = getNumericColumn( ...
        telemetryTable, ...
        "BirdPositionZMetres", ...
        height(telemetryTable), ...
        NaN);

    birdDistance = getNumericColumn( ...
        telemetryTable, ...
        "BirdDistanceMetres", ...
        height(telemetryTable), ...
        NaN);

    birdClearance = getNumericColumn( ...
        telemetryTable, ...
        "BirdClearanceMetres", ...
        height(telemetryTable), ...
        NaN);

    birdLidarHits = getNumericColumn( ...
        telemetryTable, ...
        "BirdLidarHits", ...
        height(telemetryTable), ...
        0);

    apfActive = getLogicalColumn( ...
        telemetryTable, ...
        "APFAvoidanceActive", ...
        height(telemetryTable));

    emergencyActive = getLogicalColumn( ...
        telemetryTable, ...
        "APFEmergencyActive", ...
        height(telemetryTable));

    repulsiveSpeed = getNumericColumn( ...
        telemetryTable, ...
        "RepulsiveSpeedMetresPerSecond", ...
        height(telemetryTable), ...
        0);

    tangentialSpeed = getNumericColumn( ...
        telemetryTable, ...
        "TangentialSpeedMetresPerSecond", ...
        height(telemetryTable), ...
        0);

    mapCoverage = getNumericColumn( ...
        telemetryTable, ...
        "MapCoveragePercent", ...
        height(telemetryTable), ...
        NaN);

    mapFreeCells = getNumericColumn( ...
        telemetryTable, ...
        "MapFreeCells", ...
        height(telemetryTable), ...
        NaN);

    mapOccupiedCells = getNumericColumn( ...
        telemetryTable, ...
        "MapOccupiedCells", ...
        height(telemetryTable), ...
        NaN);

    mapUpdateCount = getNumericColumn( ...
        telemetryTable, ...
        "MapUpdateCount", ...
        height(telemetryTable), ...
        NaN);

    fpvBirdVisible = getLogicalColumn( ...
        telemetryTable, ...
        "FPVBirdVisible", ...
        height(telemetryTable));

    fpvForwardObstacle = getNumericColumn( ...
        telemetryTable, ...
        "FPVForwardObstacleDistanceMetres", ...
        height(telemetryTable), ...
        NaN);

    waypointIndex = getNumericColumn( ...
        telemetryTable, ...
        "WaypointIndex", ...
        height(telemetryTable), ...
        1);

    missionState = getStringColumn( ...
        telemetryTable, ...
        "MissionState", ...
        height(telemetryTable), ...
        "UNKNOWN");

    %% Derive useful signals
    horizontalError = hypot( ...
        positionX - config.mission.goalPosition(1), ...
        positionY - config.mission.goalPosition(2));

    wrappedYawError = wrapAngleDegrees( ...
        yawDegrees - ...
        rad2deg(config.landing.targetYaw));

    commandedSpeedEstimate = estimateCommandedSpeed( ...
        time, ...
        positionX, ...
        positionY, ...
        positionZ);

    birdActiveMask = ...
        isfinite(birdClearance);

    apfNumeric = ...
        double(apfActive);

    emergencyNumeric = ...
        double(emergencyActive);

    landingStartIndex = find( ...
        startsWith(missionState, "LANDING") | ...
        missionState == "TOUCHDOWN_VERIFY" | ...
        missionState == "COMPLETE", ...
        1, ...
        "first");

    if isempty(landingStartIndex)
        landingStartIndex = height(telemetryTable);
    end

    landingStartTime = ...
        time(landingStartIndex);

    touchdownIndex = find( ...
        missionState == "TOUCHDOWN_VERIFY", ...
        1, ...
        "first");

    if isempty(touchdownIndex)

        touchdownIndex = find( ...
            missionState == "COMPLETE", ...
            1, ...
            "first");
    end

    if isempty(touchdownIndex)

        touchdownTime = time(end);

    else

        touchdownTime = time(touchdownIndex);
    end

    %% Output structure
    reportOutputs = struct();

    reportOutputs.outputDirectory = ...
        plotsDirectory;

    reportOutputs.files = strings(0, 1);

    %% Shared appearance
    figureBackground = [0.055, 0.065, 0.080];
    axesBackground = [0.075, 0.085, 0.105];
    foregroundColor = [0.92, 0.94, 0.97];
    gridColor = [0.42, 0.47, 0.54];

    %% ---------------------------------------------------------------
    % 1. Mission trajectory — top view
    % ---------------------------------------------------------------
    trajectoryTopFigure = createReportFigure( ...
        "Mission Trajectory — Top View", ...
        figureBackground);

    trajectoryTopAxes = axes( ...
        "Parent", trajectoryTopFigure);

    hold(trajectoryTopAxes, "on");

    configureAxes( ...
        trajectoryTopAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    drawRoadTopView( ...
        trajectoryTopAxes, ...
        config);

    drawOccupancyMapBackdrop( ...
        trajectoryTopAxes, ...
        occupancyGrid, ...
        config, ...
        0.22);

    plannedWaypoints = ...
        config.mission.waypoints;

    plot( ...
        trajectoryTopAxes, ...
        plannedWaypoints(:, 1), ...
        plannedWaypoints(:, 2), ...
        "--", ...
        "LineWidth", 1.4, ...
        "DisplayName", "Planned route");

    plot( ...
        trajectoryTopAxes, ...
        positionX, ...
        positionY, ...
        "-", ...
        "LineWidth", 2.4, ...
        "DisplayName", "Actual UAV trajectory");

    plotActiveTrajectorySegments( ...
        trajectoryTopAxes, ...
        positionX, ...
        positionY, ...
        apfActive, ...
        "APF active");

    validBirdPath = ...
        isfinite(birdPositionX) & ...
        isfinite(birdPositionY);

    if any(validBirdPath)

        plot( ...
            trajectoryTopAxes, ...
            birdPositionX(validBirdPath), ...
            birdPositionY(validBirdPath), ...
            "-.", ...
            "LineWidth", 1.8, ...
            "DisplayName", "Bird trajectory");
    end

    scatter( ...
        trajectoryTopAxes, ...
        plannedWaypoints(:, 1), ...
        plannedWaypoints(:, 2), ...
        55, ...
        "filled", ...
        "DisplayName", "Waypoints");

    scatter( ...
        trajectoryTopAxes, ...
        positionX(1), ...
        positionY(1), ...
        110, ...
        "^", ...
        "filled", ...
        "DisplayName", "Takeoff");

    scatter( ...
        trajectoryTopAxes, ...
        positionX(end), ...
        positionY(end), ...
        110, ...
        "v", ...
        "filled", ...
        "DisplayName", "Landing");

    closestBirdIndex = findFiniteMinimumIndex( ...
        birdClearance);

    if ~isempty(closestBirdIndex)

        scatter( ...
            trajectoryTopAxes, ...
            positionX(closestBirdIndex), ...
            positionY(closestBirdIndex), ...
            120, ...
            "p", ...
            "filled", ...
            "DisplayName", "Closest bird encounter");

        text( ...
            trajectoryTopAxes, ...
            positionX(closestBirdIndex) + 0.35, ...
            positionY(closestBirdIndex) + 0.35, ...
            sprintf( ...
                "Min clearance %.2f m", ...
                birdClearance(closestBirdIndex)), ...
            "Color", foregroundColor, ...
            "FontWeight", "bold", ...
            "FontSize", 9);
    end

    addDirectionArrows2D( ...
        trajectoryTopAxes, ...
        positionX, ...
        positionY);

    axis(trajectoryTopAxes, "equal");

    xlim( ...
        trajectoryTopAxes, ...
        config.world.xLimits);

    ylim( ...
        trajectoryTopAxes, ...
        config.world.yLimits);

    xlabel( ...
        trajectoryTopAxes, ...
        "World X position (m)");

    ylabel( ...
        trajectoryTopAxes, ...
        "World Y position (m)");

    title( ...
        trajectoryTopAxes, ...
        "Autonomous UAV Mission Trajectory — Top View");

    legend( ...
        trajectoryTopAxes, ...
        "Location", ...
        "bestoutside");

    topViewFile = fullfile( ...
        plotsDirectory, ...
        "01_mission_trajectory_top_view.png");

    exportReportFigure( ...
        trajectoryTopFigure, ...
        topViewFile);

    reportOutputs.files(end + 1, 1) = topViewFile;

    %% ---------------------------------------------------------------
    % 2. Mission trajectory — 3D
    % ---------------------------------------------------------------
    trajectory3DFigure = createReportFigure( ...
        "Mission Trajectory — 3D", ...
        figureBackground);

    trajectory3DAxes = axes( ...
        "Parent", trajectory3DFigure);

    hold(trajectory3DAxes, "on");

    configureAxes( ...
        trajectory3DAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    drawRoad3D( ...
        trajectory3DAxes, ...
        config);

    plot3( ...
        trajectory3DAxes, ...
        plannedWaypoints(:, 1), ...
        plannedWaypoints(:, 2), ...
        plannedWaypoints(:, 3), ...
        "--", ...
        "LineWidth", 1.4, ...
        "DisplayName", "Planned route");

    plot3( ...
        trajectory3DAxes, ...
        positionX, ...
        positionY, ...
        positionZ, ...
        "-", ...
        "LineWidth", 2.4, ...
        "DisplayName", "Actual UAV trajectory");

    if any(validBirdPath)

        plot3( ...
            trajectory3DAxes, ...
            birdPositionX(validBirdPath), ...
            birdPositionY(validBirdPath), ...
            birdPositionZ(validBirdPath), ...
            "-.", ...
            "LineWidth", 1.8, ...
            "DisplayName", "Bird trajectory");
    end

    scatter3( ...
        trajectory3DAxes, ...
        plannedWaypoints(:, 1), ...
        plannedWaypoints(:, 2), ...
        plannedWaypoints(:, 3), ...
        55, ...
        "filled", ...
        "DisplayName", "Waypoints");

    scatter3( ...
        trajectory3DAxes, ...
        positionX(1), ...
        positionY(1), ...
        positionZ(1), ...
        110, ...
        "^", ...
        "filled", ...
        "DisplayName", "Takeoff");

    scatter3( ...
        trajectory3DAxes, ...
        positionX(end), ...
        positionY(end), ...
        positionZ(end), ...
        110, ...
        "v", ...
        "filled", ...
        "DisplayName", "Landing");

    if ~isempty(closestBirdIndex)

        plot3( ...
            trajectory3DAxes, ...
            [ ...
                positionX(closestBirdIndex), ...
                birdPositionX(closestBirdIndex)], ...
            [ ...
                positionY(closestBirdIndex), ...
                birdPositionY(closestBirdIndex)], ...
            [ ...
                positionZ(closestBirdIndex), ...
                birdPositionZ(closestBirdIndex)], ...
            ":", ...
            "LineWidth", 2.0, ...
            "DisplayName", "Minimum-clearance line");
    end

    xlabel( ...
        trajectory3DAxes, ...
        "World X position (m)");

    ylabel( ...
        trajectory3DAxes, ...
        "World Y position (m)");

    zlabel( ...
        trajectory3DAxes, ...
        "Altitude (m)");

    title( ...
        trajectory3DAxes, ...
        "Three-Dimensional UAV Flight Path and Bird Crossing");

    xlim( ...
        trajectory3DAxes, ...
        config.world.xLimits);

    ylim( ...
        trajectory3DAxes, ...
        config.world.yLimits);

    zlim( ...
        trajectory3DAxes, ...
        config.world.zLimits);

    view( ...
        trajectory3DAxes, ...
        38, ...
        25);

    axis( ...
        trajectory3DAxes, ...
        "vis3d");

    legend( ...
        trajectory3DAxes, ...
        "Location", ...
        "bestoutside");

    trajectory3DFile = fullfile( ...
        plotsDirectory, ...
        "02_mission_trajectory_3d.png");

    exportReportFigure( ...
        trajectory3DFigure, ...
        trajectory3DFile);

    reportOutputs.files(end + 1, 1) = trajectory3DFile;

    %% ---------------------------------------------------------------
    % 3. Flight speed and wind
    % ---------------------------------------------------------------
    speedWindFigure = createReportFigure( ...
        "Flight Speed and Wind", ...
        figureBackground);

    speedWindLayout = tiledlayout( ...
        speedWindFigure, ...
        2, ...
        1, ...
        "TileSpacing", ...
        "compact", ...
        "Padding", ...
        "compact");

    speedAxes = nexttile( ...
        speedWindLayout, ...
        1);

    hold(speedAxes, "on");

    configureAxes( ...
        speedAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    addMissionPhaseBackgrounds( ...
        speedAxes, ...
        time, ...
        missionState);

    plot( ...
        speedAxes, ...
        time, ...
        groundSpeed, ...
        "LineWidth", ...
        1.8, ...
        "DisplayName", ...
        "Ground speed");

    plot( ...
        speedAxes, ...
        time, ...
        airSpeed, ...
        "LineWidth", ...
        1.6, ...
        "DisplayName", ...
        "Air-relative speed");

    plot( ...
        speedAxes, ...
        time, ...
        commandedSpeedEstimate, ...
        "--", ...
        "LineWidth", ...
        1.3, ...
        "DisplayName", ...
        "Estimated commanded speed");

    addWaypointMarkers( ...
        speedAxes, ...
        time, ...
        waypointIndex);

    xline( ...
        speedAxes, ...
        landingStartTime, ...
        ":", ...
        "Landing begins", ...
        "LabelVerticalAlignment", ...
        "middle");

    xline( ...
        speedAxes, ...
        touchdownTime, ...
        "--", ...
        "Touchdown", ...
        "LabelVerticalAlignment", ...
        "middle");

    ylabel( ...
        speedAxes, ...
        "Speed (m/s)");

    title( ...
        speedAxes, ...
        "UAV Speed Profile Across Mission Phases");

    legend( ...
        speedAxes, ...
        "Location", ...
        "bestoutside");

    windAxes = nexttile( ...
        speedWindLayout, ...
        2);

    hold(windAxes, "on");

    configureAxes( ...
        windAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    addMissionPhaseBackgrounds( ...
        windAxes, ...
        time, ...
        missionState);

    plot( ...
        windAxes, ...
        time, ...
        windSpeed, ...
        "LineWidth", ...
        1.9, ...
        "DisplayName", ...
        "Wind magnitude");

    plot( ...
        windAxes, ...
        time, ...
        windX, ...
        "LineWidth", ...
        1.1, ...
        "DisplayName", ...
        "Wind X");

    plot( ...
        windAxes, ...
        time, ...
        windY, ...
        "LineWidth", ...
        1.1, ...
        "DisplayName", ...
        "Wind Y");

    plot( ...
        windAxes, ...
        time, ...
        windZ, ...
        "LineWidth", ...
        1.1, ...
        "DisplayName", ...
        "Wind Z");

    xlabel( ...
        windAxes, ...
        "Simulation time (s)");

    ylabel( ...
        windAxes, ...
        "Wind velocity (m/s)");

    title( ...
        windAxes, ...
        "Wind Disturbance Components");

    legend( ...
        windAxes, ...
        "Location", ...
        "bestoutside");

    title( ...
        speedWindLayout, ...
        "Mission Speed, Wind Disturbance, and Phase Transitions", ...
        "Color", ...
        foregroundColor, ...
        "FontWeight", ...
        "bold");

    speedWindFile = fullfile( ...
        plotsDirectory, ...
        "03_flight_speed_and_wind.png");

    exportReportFigure( ...
        speedWindFigure, ...
        speedWindFile);

    reportOutputs.files(end + 1, 1) = speedWindFile;

    %% ---------------------------------------------------------------
    % 4. Bird encounter and APF
    % ---------------------------------------------------------------
    birdFigure = createReportFigure( ...
        "Bird Encounter and APF", ...
        figureBackground);

    birdLayout = tiledlayout( ...
        birdFigure, ...
        3, ...
        1, ...
        "TileSpacing", ...
        "compact", ...
        "Padding", ...
        "compact");

    clearanceAxes = nexttile( ...
        birdLayout, ...
        1);

    hold(clearanceAxes, "on");

    configureAxes( ...
        clearanceAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    plot( ...
        clearanceAxes, ...
        time, ...
        birdClearance, ...
        "LineWidth", ...
        2.1, ...
        "DisplayName", ...
        "Drone-to-bird surface clearance");

    yline( ...
        clearanceAxes, ...
        config.apf.safetyDistance, ...
        "--", ...
        "APF safety distance", ...
        "LabelVerticalAlignment", ...
        "bottom");

    yline( ...
        clearanceAxes, ...
        0, ...
        "-", ...
        "Collision boundary");

    if ~isempty(closestBirdIndex)

        scatter( ...
            clearanceAxes, ...
            time(closestBirdIndex), ...
            birdClearance(closestBirdIndex), ...
            95, ...
            "filled", ...
            "DisplayName", ...
            "Minimum clearance");

        text( ...
            clearanceAxes, ...
            time(closestBirdIndex), ...
            birdClearance(closestBirdIndex) + 0.18, ...
            sprintf( ...
                "%.2f m at %.2f s", ...
                birdClearance(closestBirdIndex), ...
                time(closestBirdIndex)), ...
            "Color", ...
            foregroundColor, ...
            "FontWeight", ...
            "bold", ...
            "HorizontalAlignment", ...
            "center");
    end

    ylabel( ...
        clearanceAxes, ...
        "Clearance (m)");

    title( ...
        clearanceAxes, ...
        "Dynamic Bird Encounter Clearance");

    legend( ...
        clearanceAxes, ...
        "Location", ...
        "bestoutside");

    apfAxes = nexttile( ...
        birdLayout, ...
        2);

    hold(apfAxes, "on");

    configureAxes( ...
        apfAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    area( ...
        apfAxes, ...
        time, ...
        apfNumeric, ...
        "FaceAlpha", ...
        0.28, ...
        "EdgeColor", ...
        "none", ...
        "DisplayName", ...
        "APF active");

    stairs( ...
        apfAxes, ...
        time, ...
        emergencyNumeric, ...
        "LineWidth", ...
        1.6, ...
        "DisplayName", ...
        "Emergency avoidance");

    stairs( ...
        apfAxes, ...
        time, ...
        double(birdLidarHits > 0), ...
        "LineWidth", ...
        1.4, ...
        "DisplayName", ...
        "Bird detected by LiDAR");

    stairs( ...
        apfAxes, ...
        time, ...
        double(fpvBirdVisible), ...
        "LineWidth", ...
        1.2, ...
        "DisplayName", ...
        "Bird visible in FPV");

    ylim( ...
        apfAxes, ...
        [-0.05, 1.15]);

    ylabel( ...
        apfAxes, ...
        "Status");

    title( ...
        apfAxes, ...
        "Perception and Avoidance Activation Timeline");

    legend( ...
        apfAxes, ...
        "Location", ...
        "bestoutside");

    controllerAxes = nexttile( ...
        birdLayout, ...
        3);

    hold(controllerAxes, "on");

    configureAxes( ...
        controllerAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    plot( ...
        controllerAxes, ...
        time, ...
        repulsiveSpeed, ...
        "LineWidth", ...
        1.8, ...
        "DisplayName", ...
        "Repulsive component");

    plot( ...
        controllerAxes, ...
        time, ...
        tangentialSpeed, ...
        "LineWidth", ...
        1.8, ...
        "DisplayName", ...
        "Tangential component");

    yyaxis( ...
        controllerAxes, ...
        "right");

    plot( ...
        controllerAxes, ...
        time, ...
        birdLidarHits, ...
        ":", ...
        "LineWidth", ...
        1.5, ...
        "DisplayName", ...
        "Bird LiDAR hits");

    ylabel( ...
        controllerAxes, ...
        "LiDAR hit count");

    yyaxis( ...
        controllerAxes, ...
        "left");

    xlabel( ...
        controllerAxes, ...
        "Simulation time (s)");

    ylabel( ...
        controllerAxes, ...
        "Avoidance velocity (m/s)");

    title( ...
        controllerAxes, ...
        "APF Controller Response During Bird Crossing");

    legend( ...
        controllerAxes, ...
        "Location", ...
        "bestoutside");

    title( ...
        birdLayout, ...
        "Dynamic Bird Detection, Clearance, and APF Response", ...
        "Color", ...
        foregroundColor, ...
        "FontWeight", ...
        "bold");

    birdFile = fullfile( ...
        plotsDirectory, ...
        "04_bird_encounter_and_apf.png");

    exportReportFigure( ...
        birdFigure, ...
        birdFile);

    reportOutputs.files(end + 1, 1) = birdFile;

    %% ---------------------------------------------------------------
    % 5. Final occupancy map
    % ---------------------------------------------------------------
    occupancyFigure = createReportFigure( ...
        "Final Occupancy Map", ...
        figureBackground);

    occupancyAxes = axes( ...
        "Parent", ...
        occupancyFigure);

    configureAxes( ...
        occupancyAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    hold( ...
        occupancyAxes, ...
        "on");

    occupancyProbability = getOccupancyProbability( ...
        occupancyGrid);

    [mapX, mapY] = getOccupancyCoordinates( ...
        occupancyGrid, ...
        config, ...
        size(occupancyProbability));

    imagesc( ...
        occupancyAxes, ...
        mapX, ...
        mapY, ...
        occupancyProbability);

    set( ...
        occupancyAxes, ...
        "YDir", ...
        "normal");

    colormap( ...
        occupancyAxes, ...
        gray(256));

    colorbarHandle = colorbar( ...
        occupancyAxes);

    colorbarHandle.Label.String = ...
        "Occupancy probability";

    colorbarHandle.Color = ...
        foregroundColor;

    plot( ...
        occupancyAxes, ...
        positionX, ...
        positionY, ...
        "-", ...
        "LineWidth", ...
        2.2, ...
        "DisplayName", ...
        "UAV trajectory");

    plot( ...
        occupancyAxes, ...
        plannedWaypoints(:, 1), ...
        plannedWaypoints(:, 2), ...
        "--", ...
        "LineWidth", ...
        1.2, ...
        "DisplayName", ...
        "Planned route");

    scatter( ...
        occupancyAxes, ...
        positionX(1), ...
        positionY(1), ...
        100, ...
        "^", ...
        "filled", ...
        "DisplayName", ...
        "Takeoff");

    scatter( ...
        occupancyAxes, ...
        positionX(end), ...
        positionY(end), ...
        100, ...
        "v", ...
        "filled", ...
        "DisplayName", ...
        "Landing");

    axis( ...
        occupancyAxes, ...
        "equal");

    xlim( ...
        occupancyAxes, ...
        config.world.xLimits);

    ylim( ...
        occupancyAxes, ...
        config.world.yLimits);

    xlabel( ...
        occupancyAxes, ...
        "World X position (m)");

    ylabel( ...
        occupancyAxes, ...
        "World Y position (m)");

    title( ...
        occupancyAxes, ...
        sprintf( ...
            "Final Occupancy Map — %.1f%% Coverage", ...
            mapCoverage(end)));

    legend( ...
        occupancyAxes, ...
        "Location", ...
        "bestoutside");

    occupancyFile = fullfile( ...
        plotsDirectory, ...
        "05_final_occupancy_map.png");

    exportReportFigure( ...
        occupancyFigure, ...
        occupancyFile);

    reportOutputs.files(end + 1, 1) = occupancyFile;

    %% ---------------------------------------------------------------
    % 6. Mapping progress
    % ---------------------------------------------------------------
    mappingFigure = createReportFigure( ...
        "Mapping Progress", ...
        figureBackground);

    mappingLayout = tiledlayout( ...
        mappingFigure, ...
        2, ...
        1, ...
        "TileSpacing", ...
        "compact", ...
        "Padding", ...
        "compact");

    coverageAxes = nexttile( ...
        mappingLayout, ...
        1);

    hold(coverageAxes, "on");

    configureAxes( ...
        coverageAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    plot( ...
        coverageAxes, ...
        time, ...
        mapCoverage, ...
        "LineWidth", ...
        2.1, ...
        "DisplayName", ...
        "Map coverage");

    yline( ...
        coverageAxes, ...
        80, ...
        "--", ...
        "80% validation threshold");

    ylabel( ...
        coverageAxes, ...
        "Coverage (%)");

    ylim( ...
        coverageAxes, ...
        [0, 100]);

    title( ...
        coverageAxes, ...
        "Occupancy-Map Coverage Over Time");

    legend( ...
        coverageAxes, ...
        "Location", ...
        "bestoutside");

    cellAxes = nexttile( ...
        mappingLayout, ...
        2);

    hold(cellAxes, "on");

    configureAxes( ...
        cellAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    yyaxis( ...
        cellAxes, ...
        "left");

    plot( ...
        cellAxes, ...
        time, ...
        mapFreeCells, ...
        "LineWidth", ...
        1.7, ...
        "DisplayName", ...
        "Free cells");

    plot( ...
        cellAxes, ...
        time, ...
        mapOccupiedCells, ...
        "LineWidth", ...
        1.7, ...
        "DisplayName", ...
        "Occupied cells");

    ylabel( ...
        cellAxes, ...
        "Mapped cell count");

    yyaxis( ...
        cellAxes, ...
        "right");

    plot( ...
        cellAxes, ...
        time, ...
        mapUpdateCount, ...
        "--", ...
        "LineWidth", ...
        1.5, ...
        "DisplayName", ...
        "Map updates");

    ylabel( ...
        cellAxes, ...
        "Cumulative updates");

    xlabel( ...
        cellAxes, ...
        "Simulation time (s)");

    title( ...
        cellAxes, ...
        "Mapped Cells and Occupancy-Grid Updates");

    legend( ...
        cellAxes, ...
        "Location", ...
        "bestoutside");

    title( ...
        mappingLayout, ...
        "Live Occupancy Mapping Performance", ...
        "Color", ...
        foregroundColor, ...
        "FontWeight", ...
        "bold");

    mappingFile = fullfile( ...
        plotsDirectory, ...
        "06_mapping_progress.png");

    exportReportFigure( ...
        mappingFigure, ...
        mappingFile);

    reportOutputs.files(end + 1, 1) = mappingFile;

    %% ---------------------------------------------------------------
    % 7. Refined landing performance
    % ---------------------------------------------------------------
    landingFigure = createReportFigure( ...
        "Refined Landing Performance", ...
        figureBackground);

    landingLayout = tiledlayout( ...
        landingFigure, ...
        2, ...
        2, ...
        "TileSpacing", ...
        "compact", ...
        "Padding", ...
        "compact");

    landingAltitudeAxes = nexttile( ...
        landingLayout, ...
        1);

    hold(landingAltitudeAxes, "on");

    configureAxes( ...
        landingAltitudeAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    addLandingPhaseBackgrounds( ...
        landingAltitudeAxes, ...
        time, ...
        missionState);

    plot( ...
        landingAltitudeAxes, ...
        time, ...
        positionZ, ...
        "LineWidth", ...
        2.1, ...
        "DisplayName", ...
        "Altitude");

    yline( ...
        landingAltitudeAxes, ...
        config.landing.approachAltitude, ...
        ":", ...
        "Approach altitude");

    yline( ...
        landingAltitudeAxes, ...
        config.landing.flareAltitude, ...
        "--", ...
        "Flare altitude");

    yline( ...
        landingAltitudeAxes, ...
        config.landing.touchdownHeight, ...
        "-.", ...
        "Touchdown height");

    xlim( ...
        landingAltitudeAxes, ...
        [landingStartTime, time(end)]);

    ylabel( ...
        landingAltitudeAxes, ...
        "Altitude (m)");

    title( ...
        landingAltitudeAxes, ...
        "Landing Altitude Profile");

    legend( ...
        landingAltitudeAxes, ...
        "Location", ...
        "best");

    landingVelocityAxes = nexttile( ...
        landingLayout, ...
        2);

    hold(landingVelocityAxes, "on");

    configureAxes( ...
        landingVelocityAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    addLandingPhaseBackgrounds( ...
        landingVelocityAxes, ...
        time, ...
        missionState);

    plot( ...
        landingVelocityAxes, ...
        time, ...
        groundVelocityZ, ...
        "LineWidth", ...
        2.0, ...
        "DisplayName", ...
        "Vertical ground velocity");

    yline( ...
        landingVelocityAxes, ...
        -config.landing.maximumTouchdownVerticalSpeed, ...
        "--", ...
        "Touchdown limit");

    yline( ...
        landingVelocityAxes, ...
        0, ...
        ":");

    xlim( ...
        landingVelocityAxes, ...
        [landingStartTime, time(end)]);

    ylabel( ...
        landingVelocityAxes, ...
        "Vertical velocity (m/s)");

    title( ...
        landingVelocityAxes, ...
        "Vertical Descent and Touchdown Speed");

    legend( ...
        landingVelocityAxes, ...
        "Location", ...
        "best");

    landingPositionAxes = nexttile( ...
        landingLayout, ...
        3);

    hold(landingPositionAxes, "on");

    configureAxes( ...
        landingPositionAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    addLandingPhaseBackgrounds( ...
        landingPositionAxes, ...
        time, ...
        missionState);

    plot( ...
        landingPositionAxes, ...
        time, ...
        horizontalError, ...
        "LineWidth", ...
        2.0, ...
        "DisplayName", ...
        "Horizontal landing error");

    yline( ...
        landingPositionAxes, ...
        config.landing.touchdownHorizontalTolerance, ...
        "--", ...
        "Touchdown tolerance");

    xlim( ...
        landingPositionAxes, ...
        [landingStartTime, time(end)]);

    xlabel( ...
        landingPositionAxes, ...
        "Simulation time (s)");

    ylabel( ...
        landingPositionAxes, ...
        "Horizontal error (m)");

    title( ...
        landingPositionAxes, ...
        "Landing-Pad Position Alignment");

    legend( ...
        landingPositionAxes, ...
        "Location", ...
        "best");

    landingYawAxes = nexttile( ...
        landingLayout, ...
        4);

    hold(landingYawAxes, "on");

    configureAxes( ...
        landingYawAxes, ...
        axesBackground, ...
        foregroundColor, ...
        gridColor);

    addLandingPhaseBackgrounds( ...
        landingYawAxes, ...
        time, ...
        missionState);

    plot( ...
        landingYawAxes, ...
        time, ...
        wrappedYawError, ...
        "LineWidth", ...
        2.0, ...
        "DisplayName", ...
        "Landing yaw error");

    yline( ...
        landingYawAxes, ...
        rad2deg(config.landing.yawTolerance), ...
        "--", ...
        "Positive tolerance");

    yline( ...
        landingYawAxes, ...
        -rad2deg(config.landing.yawTolerance), ...
        "--", ...
        "Negative tolerance");

    yline( ...
        landingYawAxes, ...
        0, ...
        ":");

    xlim( ...
        landingYawAxes, ...
        [landingStartTime, time(end)]);

    xlabel( ...
        landingYawAxes, ...
        "Simulation time (s)");

    ylabel( ...
        landingYawAxes, ...
        "Yaw error (deg)");

    title( ...
        landingYawAxes, ...
        "Final Heading Alignment");

    legend( ...
        landingYawAxes, ...
        "Location", ...
        "best");

    title( ...
        landingLayout, ...
        "Refined Landing: Approach, Descent, Flare, and Touchdown", ...
        "Color", ...
        foregroundColor, ...
        "FontWeight", ...
        "bold");

    landingFile = fullfile( ...
        plotsDirectory, ...
        "07_refined_landing_performance.png");

    exportReportFigure( ...
        landingFigure, ...
        landingFile);

    reportOutputs.files(end + 1, 1) = landingFile;

    %% ---------------------------------------------------------------
    % 8. Mission performance summary
    % ---------------------------------------------------------------
    summaryFigure = createReportFigure( ...
        "Mission Performance Summary", ...
        figureBackground);

    summaryAxes = axes( ...
        "Parent", ...
        summaryFigure, ...
        "Position", ...
        [0.04, 0.06, 0.92, 0.88]);

    axis( ...
        summaryAxes, ...
        [0, 1, 0, 1]);

    axis( ...
        summaryAxes, ...
        "off");

    title( ...
        summaryAxes, ...
        "Autonomous UAV Mission Performance Summary", ...
        "Color", ...
        foregroundColor, ...
        "FontSize", ...
        20, ...
        "FontWeight", ...
        "bold");

    metricNames = {
        "Mission completion"
        "Simulation time"
        "Distance travelled"
        "Maximum wind speed"
        "Average wind speed"
        "Minimum bird clearance"
        "APF activation steps"
        "Bird-avoidance activations"
        "Occupancy-map coverage"
        "Telemetry samples"
        "Video frames"
        "Touchdown total speed"
        "Touchdown vertical speed"
        "Touchdown verification"
    };

    metricValues = {
        getSummaryText( ...
            summaryData, ...
            "MissionCompleted", ...
            "Successful")
        formatSummaryMetric( ...
            summaryData, ...
            "SimulationTimeSeconds", ...
            time(end), ...
            "%.2f s")
        formatSummaryMetric( ...
            summaryData, ...
            "DistanceTravelledMetres", ...
            distanceTravelled(end), ...
            "%.2f m")
        formatSummaryMetric( ...
            summaryData, ...
            "MaximumWindSpeedMetresPerSecond", ...
            max(windSpeed, [], "omitnan"), ...
            "%.2f m/s")
        formatSummaryMetric( ...
            summaryData, ...
            "AverageWindSpeedMetresPerSecond", ...
            mean(windSpeed, "omitnan"), ...
            "%.2f m/s")
        formatSummaryMetric( ...
            summaryData, ...
            "MinimumBirdClearanceMetres", ...
            min(birdClearance, [], "omitnan"), ...
            "%.2f m")
        formatSummaryMetric( ...
            summaryData, ...
            "TotalAPFActivationSteps", ...
            sum(apfActive), ...
            "%.0f")
        formatSummaryMetric( ...
            summaryData, ...
            "BirdAvoidanceActivationSteps", ...
            sum(apfActive & birdLidarHits > 0), ...
            "%.0f")
        formatSummaryMetric( ...
            summaryData, ...
            "OccupancyCoveragePercent", ...
            mapCoverage(end), ...
            "%.1f %%")
        formatSummaryMetric( ...
            summaryData, ...
            "TelemetrySamples", ...
            height(telemetryTable), ...
            "%.0f")
        formatSummaryMetric( ...
            summaryData, ...
            "VideoFrames", ...
            NaN, ...
            "%.0f")
        formatSummaryMetric( ...
            summaryData, ...
            "TouchdownTotalSpeedMetresPerSecond", ...
            groundSpeed( ...
                min( ...
                    max(touchdownIndex, 1), ...
                    numel(groundSpeed))), ...
            "%.2f m/s")
        formatSummaryMetric( ...
            summaryData, ...
            "TouchdownVerticalSpeedMetresPerSecond", ...
            abs(groundVelocityZ( ...
                min( ...
                    max(touchdownIndex, 1), ...
                    numel(groundVelocityZ)))), ...
            "%.2f m/s")
        formatSummaryMetric( ...
            summaryData, ...
            "TouchdownVerificationSeconds", ...
            config.landing.touchdownVerificationTime, ...
            "%.2f s")
    };

    numberOfMetrics = ...
        numel(metricNames);

    numberOfColumns = 2;
    numberOfRows = ceil( ...
        numberOfMetrics / ...
        numberOfColumns);

    cardWidth = 0.42;
    cardHeight = 0.095;
    horizontalGap = 0.08;
    verticalGap = 0.022;

    startX = 0.04;
    startY = 0.80;

    for metricIndex = 1:numberOfMetrics

        columnIndex = mod( ...
            metricIndex - 1, ...
            numberOfColumns);

        rowIndex = floor( ...
            (metricIndex - 1) / ...
            numberOfColumns);

        cardX = ...
            startX + ...
            columnIndex * ...
            (cardWidth + horizontalGap);

        cardY = ...
            startY - ...
            rowIndex * ...
            (cardHeight + verticalGap);

        rectangle( ...
            summaryAxes, ...
            "Position", ...
            [ ...
                cardX, ...
                cardY, ...
                cardWidth, ...
                cardHeight], ...
            "Curvature", ...
            0.08, ...
            "FaceColor", ...
            axesBackground, ...
            "EdgeColor", ...
            [0.30, 0.40, 0.55], ...
            "LineWidth", ...
            1.2);

        text( ...
            summaryAxes, ...
            cardX + 0.025, ...
            cardY + 0.063, ...
            metricNames{metricIndex}, ...
            "Color", ...
            [0.66, 0.74, 0.85], ...
            "FontSize", ...
            9, ...
            "FontWeight", ...
            "bold");

        text( ...
            summaryAxes, ...
            cardX + 0.025, ...
            cardY + 0.026, ...
            metricValues{metricIndex}, ...
            "Color", ...
            foregroundColor, ...
            "FontSize", ...
            13, ...
            "FontWeight", ...
            "bold");
    end

    text( ...
        summaryAxes, ...
        0.50, ...
        0.015, ...
        "Autonomous UAV Navigation and Dynamic Obstacle Avoidance in MATLAB", ...
        "HorizontalAlignment", ...
        "center", ...
        "Color", ...
        [0.65, 0.75, 0.88], ...
        "FontSize", ...
        10);

    summaryFile = fullfile( ...
        plotsDirectory, ...
        "08_mission_performance_summary.png");

    exportReportFigure( ...
        summaryFigure, ...
        summaryFile);

    reportOutputs.files(end + 1, 1) = summaryFile;

    %% Close report figures
    close( ...
        trajectoryTopFigure, ...
        trajectory3DFigure, ...
        speedWindFigure, ...
        birdFigure, ...
        occupancyFigure, ...
        mappingFigure, ...
        landingFigure, ...
        summaryFigure);

    %% Print generated output list
    fprintf("\nGenerated portfolio-quality performance plots:\n");

    for fileIndex = 1:numel(reportOutputs.files)

        fprintf( ...
            "%s\n", ...
            reportOutputs.files(fileIndex));
    end
end


function telemetryTable = loadTelemetryTable(telemetryInput)
%LOADTELEMETRYTABLE Load telemetry from a table or CSV path.

    if istable(telemetryInput)

        telemetryTable = ...
            telemetryInput;

        return;
    end

    telemetryPath = ...
        string(telemetryInput);

    if ~isfile(telemetryPath)

        error( ...
            "MissionReport:TelemetryFileMissing", ...
            "Telemetry file was not found: %s", ...
            telemetryPath);
    end

    importOptions = ...
        detectImportOptions( ...
            telemetryPath, ...
            "VariableNamingRule", ...
            "preserve");

    telemetryTable = ...
        readtable( ...
            telemetryPath, ...
            importOptions);
end


function summaryData = loadSummaryData(summaryInput)
%LOADSUMMARYDATA Load summary data from supported input formats.

    if istable(summaryInput)

        summaryData = ...
            summaryInput;

        return;
    end

    if isstruct(summaryInput)

        summaryData = ...
            summaryInput;

        return;
    end

    summaryPath = ...
        string(summaryInput);

    if isfile(summaryPath)

        importOptions = ...
            detectImportOptions( ...
                summaryPath, ...
                "VariableNamingRule", ...
                "preserve");

        summaryData = ...
            readtable( ...
                summaryPath, ...
                importOptions);

    else

        summaryData = struct();
    end
end


function outputFigure = createReportFigure(figureName, backgroundColor)
%CREATEREPORTFIGURE Create a consistent report figure.

    outputFigure = figure( ...
        "Name", ...
        figureName, ...
        "NumberTitle", ...
        "off", ...
        "Color", ...
        backgroundColor, ...
        "Position", ...
        [60, 40, 1500, 900], ...
        "Visible", ...
        "on");
end


function configureAxes( ...
    axesHandle, backgroundColor, foregroundColor, gridColor)
%CONFIGUREAXES Apply consistent report styling.

    axesHandle.Color = ...
        backgroundColor;

    axesHandle.XColor = ...
        foregroundColor;

    axesHandle.YColor = ...
        foregroundColor;

    axesHandle.ZColor = ...
        foregroundColor;

    axesHandle.GridColor = ...
        gridColor;

    axesHandle.MinorGridColor = ...
        gridColor;

    axesHandle.GridAlpha = ...
        0.32;

    axesHandle.MinorGridAlpha = ...
        0.14;

    axesHandle.FontName = ...
        "Arial";

    axesHandle.FontSize = ...
        10;

    axesHandle.LineWidth = ...
        1.0;

    grid( ...
        axesHandle, ...
        "on");

    box( ...
        axesHandle, ...
        "on");
end


function exportReportFigure(figureHandle, outputFile)
%EXPORTREPORTFIGURE Export a clean high-resolution PNG.
%
% Axes toolbars are hidden before export so the saved image contains only
% the report content.

    axesHandles = findall( ...
        figureHandle, ...
        "Type", ...
        "axes");

    for axesIndex = 1:numel(axesHandles)

        try
            axesHandles(axesIndex).Toolbar.Visible = "off";
        catch
            % Older or specialized axes may not expose a toolbar object.
        end
    end

    drawnow;

    exportgraphics( ...
        figureHandle, ...
        outputFile, ...
        "Resolution", ...
        220);
end


function drawRoadTopView(axesHandle, config)
%DRAWROADTOPVIEW Draw a realistic road backdrop.

    roadX = config.world.xLimits;
    roadHalfWidth = 2.2;

    patch( ...
        axesHandle, ...
        [roadX(1), roadX(2), roadX(2), roadX(1)], ...
        [-roadHalfWidth, -roadHalfWidth, roadHalfWidth, roadHalfWidth], ...
        [0.16, 0.17, 0.19], ...
        "EdgeColor", ...
        "none", ...
        "HandleVisibility", ...
        "off");

    plot( ...
        axesHandle, ...
        roadX, ...
        [-roadHalfWidth, -roadHalfWidth], ...
        "-", ...
        "LineWidth", ...
        1.5, ...
        "HandleVisibility", ...
        "off");

    plot( ...
        axesHandle, ...
        roadX, ...
        [roadHalfWidth, roadHalfWidth], ...
        "-", ...
        "LineWidth", ...
        1.5, ...
        "HandleVisibility", ...
        "off");

    laneDashLength = 1.2;
    laneGapLength = 1.0;

    dashStart = ...
        roadX(1);

    while dashStart < roadX(2)

        dashEnd = min( ...
            dashStart + laneDashLength, ...
            roadX(2));

        plot( ...
            axesHandle, ...
            [dashStart, dashEnd], ...
            [0, 0], ...
            "-", ...
            "LineWidth", ...
            1.7, ...
            "HandleVisibility", ...
            "off");

        dashStart = ...
            dashEnd + laneGapLength;
    end
end


function drawRoad3D(axesHandle, config)
%DRAWROAD3D Draw the road surface in the 3D mission figure.

    roadX = config.world.xLimits;
    roadHalfWidth = 2.2;

    patch( ...
        axesHandle, ...
        [roadX(1), roadX(2), roadX(2), roadX(1)], ...
        [-roadHalfWidth, -roadHalfWidth, roadHalfWidth, roadHalfWidth], ...
        [0, 0, 0, 0], ...
        [0.16, 0.17, 0.19], ...
        "EdgeColor", ...
        [0.60, 0.62, 0.66], ...
        "FaceAlpha", ...
        0.92, ...
        "HandleVisibility", ...
        "off");

    laneDashLength = 1.2;
    laneGapLength = 1.0;

    dashStart = roadX(1);

    while dashStart < roadX(2)

        dashEnd = min( ...
            dashStart + laneDashLength, ...
            roadX(2));

        plot3( ...
            axesHandle, ...
            [dashStart, dashEnd], ...
            [0, 0], ...
            [0.015, 0.015], ...
            "-", ...
            "LineWidth", ...
            1.8, ...
            "HandleVisibility", ...
            "off");

        dashStart = ...
            dashEnd + laneGapLength;
    end
end


function drawOccupancyMapBackdrop( ...
    axesHandle, occupancyGrid, config, transparency)
%DRAWOCCUPANCYMAPBACKDROP Draw occupied-map cells behind trajectory.

    occupancyProbability = ...
        getOccupancyProbability( ...
            occupancyGrid);

    if isempty(occupancyProbability)
        return;
    end

    occupiedMask = ...
        occupancyProbability >= ...
        config.mapping.occupiedThreshold;

    [mapX, mapY] = getOccupancyCoordinates( ...
        occupancyGrid, ...
        config, ...
        size(occupiedMask));

    imagesc( ...
        axesHandle, ...
        mapX, ...
        mapY, ...
        occupiedMask);

    set( ...
        axesHandle, ...
        "YDir", ...
        "normal");

    occupancyImage = ...
        axesHandle.Children(1);

    occupancyImage.AlphaData = ...
        double(occupiedMask) * ...
        transparency;
end


function occupancyProbability = getOccupancyProbability(occupancyGrid)
%GETOCCUPANCYPROBABILITY Extract occupancy probabilities robustly.

    occupancyProbability = [];

    candidateFields = {
        "probabilityGrid"
        "occupancyProbability"
        "probability"
        "map"
        "grid"
    };

    for candidateIndex = 1:numel(candidateFields)

        fieldName = ...
            candidateFields{candidateIndex};

        if isfield(occupancyGrid, fieldName)

            candidateValue = ...
                occupancyGrid.(fieldName);

            if isnumeric(candidateValue) && ...
                    ismatrix(candidateValue)

                occupancyProbability = ...
                    double(candidateValue);

                break;
            end
        end
    end

    if isempty(occupancyProbability) && ...
            isfield(occupancyGrid, "logOdds")

        logOdds = ...
            double(occupancyGrid.logOdds);

        occupancyProbability = ...
            1 ./ ...
            (1 + exp(-logOdds));
    end

    if isempty(occupancyProbability)

        occupancyProbability = ...
            zeros( ...
                48, ...
                120);
    end

    if max( ...
            occupancyProbability, ...
            [], ...
            "all", ...
            "omitnan") > 1

        occupancyProbability = ...
            1 ./ ...
            (1 + exp(-occupancyProbability));
    end
end


function [mapX, mapY] = getOccupancyCoordinates( ...
    occupancyGrid, config, gridSize)
%GETOCCUPANCYCOORDINATES Determine occupancy map axis coordinates.

    if isfield(occupancyGrid, "xCoordinates")

        mapX = ...
            occupancyGrid.xCoordinates;

    else

        mapX = linspace( ...
            config.world.xLimits(1), ...
            config.world.xLimits(2), ...
            gridSize(2));
    end

    if isfield(occupancyGrid, "yCoordinates")

        mapY = ...
            occupancyGrid.yCoordinates;

    else

        mapY = linspace( ...
            config.world.yLimits(1), ...
            config.world.yLimits(2), ...
            gridSize(1));
    end
end


function plotActiveTrajectorySegments( ...
    axesHandle, positionX, positionY, activeMask, displayName)
%PLOTACTIVETRAJECTORYSEGMENTS Highlight active-controller path sections.

    activeIndices = find( ...
        activeMask);

    if isempty(activeIndices)
        return;
    end

    segmentStart = ...
        activeIndices(1);

    previousIndex = ...
        activeIndices(1);

    legendUsed = false;

    for activeIndex = 2:numel(activeIndices)

        currentIndex = ...
            activeIndices(activeIndex);

        if currentIndex > previousIndex + 1

            legendUsed = plotOneActiveSegment( ...
                axesHandle, ...
                positionX, ...
                positionY, ...
                segmentStart, ...
                previousIndex, ...
                displayName, ...
                legendUsed);

            segmentStart = ...
                currentIndex;
        end

        previousIndex = ...
            currentIndex;
    end

    plotOneActiveSegment( ...
        axesHandle, ...
        positionX, ...
        positionY, ...
        segmentStart, ...
        previousIndex, ...
        displayName, ...
        legendUsed);
end


function legendUsed = plotOneActiveSegment( ...
    axesHandle, positionX, positionY, ...
    startIndex, endIndex, displayName, legendUsed)
%PLOTONEACTIVESEGMENT Draw one contiguous APF trajectory segment.

    segmentIndices = ...
        max(1, startIndex - 1): ...
        min(numel(positionX), endIndex + 1);

    if legendUsed

        plot( ...
            axesHandle, ...
            positionX(segmentIndices), ...
            positionY(segmentIndices), ...
            "-", ...
            "LineWidth", ...
            4.0, ...
            "HandleVisibility", ...
            "off");

    else

        plot( ...
            axesHandle, ...
            positionX(segmentIndices), ...
            positionY(segmentIndices), ...
            "-", ...
            "LineWidth", ...
            4.0, ...
            "DisplayName", ...
            displayName);

        legendUsed = true;
    end
end


function addDirectionArrows2D(axesHandle, xData, yData)
%ADDDIRECTIONARROWS2D Add sparse direction arrows to the path.

    validMask = ...
        isfinite(xData) & ...
        isfinite(yData);

    validIndices = ...
        find(validMask);

    if numel(validIndices) < 4
        return;
    end

    arrowIndices = round( ...
        linspace( ...
            validIndices(1), ...
            validIndices(end) - 1, ...
            7));

    for arrowIndex = arrowIndices

        nextIndex = ...
            min( ...
                arrowIndex + 2, ...
                numel(xData));

        deltaX = ...
            xData(nextIndex) - ...
            xData(arrowIndex);

        deltaY = ...
            yData(nextIndex) - ...
            yData(arrowIndex);

        if hypot(deltaX, deltaY) < 1e-4
            continue;
        end

        quiver( ...
            axesHandle, ...
            xData(arrowIndex), ...
            yData(arrowIndex), ...
            deltaX, ...
            deltaY, ...
            0, ...
            "LineWidth", ...
            1.1, ...
            "MaxHeadSize", ...
            1.8, ...
            "HandleVisibility", ...
            "off");
    end
end


function addMissionPhaseBackgrounds( ...
    axesHandle, time, missionState)
%ADDMISSIONPHASEBACKGROUNDS Add subtle mission-state regions.

    stateNames = {
        "TAKEOFF"
        "NAVIGATION"
        "LANDING_APPROACH"
        "LANDING_DESCENT"
        "LANDING_FLARE"
        "TOUCHDOWN_VERIFY"
        "COMPLETE"
    };

    axesLimits = ...
        ylim(axesHandle);

    for stateIndex = 1:numel(stateNames)

        currentState = ...
            stateNames{stateIndex};

        stateMask = ...
            missionState == currentState;

        stateRanges = ...
            logicalRanges( ...
                stateMask);

        for rangeIndex = 1:size(stateRanges, 1)

            startIndex = ...
                stateRanges(rangeIndex, 1);

            endIndex = ...
                stateRanges(rangeIndex, 2);

            patch( ...
                axesHandle, ...
                [ ...
                    time(startIndex), ...
                    time(endIndex), ...
                    time(endIndex), ...
                    time(startIndex)], ...
                [ ...
                    axesLimits(1), ...
                    axesLimits(1), ...
                    axesLimits(2), ...
                    axesLimits(2)], ...
                0.5 * ones(1, 3), ...
                "FaceAlpha", ...
                0.055, ...
                "EdgeColor", ...
                "none", ...
                "HandleVisibility", ...
                "off");
        end
    end

    uistack( ...
        findobj( ...
            axesHandle, ...
            "Type", ...
            "patch"), ...
        "bottom");
end


function addLandingPhaseBackgrounds( ...
    axesHandle, time, missionState)
%ADDLANDINGPHASEBACKGROUNDS Highlight landing phases.

    landingStates = {
        "LANDING_APPROACH"
        "LANDING_DESCENT"
        "LANDING_FLARE"
        "TOUCHDOWN_VERIFY"
        "COMPLETE"
    };

    axesLimits = ...
        ylim(axesHandle);

    for phaseIndex = 1:numel(landingStates)

        phaseMask = ...
            missionState == ...
            landingStates{phaseIndex};

        phaseRanges = ...
            logicalRanges( ...
                phaseMask);

        for rangeIndex = 1:size(phaseRanges, 1)

            startIndex = ...
                phaseRanges(rangeIndex, 1);

            endIndex = ...
                phaseRanges(rangeIndex, 2);

            patch( ...
                axesHandle, ...
                [ ...
                    time(startIndex), ...
                    time(endIndex), ...
                    time(endIndex), ...
                    time(startIndex)], ...
                [ ...
                    axesLimits(1), ...
                    axesLimits(1), ...
                    axesLimits(2), ...
                    axesLimits(2)], ...
                0.6 * ones(1, 3), ...
                "FaceAlpha", ...
                0.075, ...
                "EdgeColor", ...
                "none", ...
                "HandleVisibility", ...
                "off");
        end
    end

    uistack( ...
        findobj( ...
            axesHandle, ...
            "Type", ...
            "patch"), ...
        "bottom");
end


function ranges = logicalRanges(logicalMask)
%LOGICALRANGES Return start and end indices of true regions.

    logicalMask = ...
        logical(logicalMask(:));

    paddedMask = [
        false
        logicalMask
        false
    ];

    transitions = ...
        diff(paddedMask);

    startIndices = ...
        find(transitions == 1);

    endIndices = ...
        find(transitions == -1) - 1;

    ranges = [
        startIndices, ...
        endIndices
    ];
end


function addWaypointMarkers(axesHandle, time, waypointIndex)
%ADDWAYPOINTMARKERS Add vertical lines at waypoint transitions.

    transitionIndices = ...
        find(diff(waypointIndex) > 0) + 1;

    for transitionIndex = transitionIndices(:)'

        xline( ...
            axesHandle, ...
            time(transitionIndex), ...
            ":", ...
            sprintf( ...
                "WP %d", ...
                waypointIndex(transitionIndex)), ...
            "LabelVerticalAlignment", ...
            "bottom", ...
            "HandleVisibility", ...
            "off");
    end
end


function commandedSpeed = estimateCommandedSpeed( ...
    time, positionX, positionY, positionZ)
%ESTIMATECOMMANDEDSPEED Estimate path command speed from position changes.

    deltaTime = [
        NaN
        diff(time)
    ];

    distanceStep = [
        0
        sqrt( ...
            diff(positionX).^2 + ...
            diff(positionY).^2 + ...
            diff(positionZ).^2)
    ];

    commandedSpeed = ...
        distanceStep ./ ...
        max(deltaTime, eps);

    commandedSpeed(1) = ...
        commandedSpeed( ...
            min(2, numel(commandedSpeed)));

    commandedSpeed = ...
        movmean( ...
            commandedSpeed, ...
            5, ...
            "omitnan");
end


function minimumIndex = findFiniteMinimumIndex(inputData)
%FINDFINITEMINIMUMINDEX Find the index of the minimum finite value.

    validIndices = ...
        find(isfinite(inputData));

    if isempty(validIndices)

        minimumIndex = [];

        return;
    end

    [~, localIndex] = min( ...
        inputData(validIndices));

    minimumIndex = ...
        validIndices(localIndex);
end


function outputColumn = getNumericColumn( ...
    inputTable, variableName, expectedRows, defaultValue)
%GETNUMERICCOLUMN Read a numeric telemetry column safely.

    if ismember( ...
            variableName, ...
            inputTable.Properties.VariableNames)

        outputColumn = ...
            double( ...
                inputTable.(variableName));

        outputColumn = ...
            outputColumn(:);

    else

        outputColumn = ...
            repmat( ...
                defaultValue, ...
                expectedRows, ...
                1);
    end
end


function outputColumn = getLogicalColumn( ...
    inputTable, variableName, expectedRows)
%GETLOGICALCOLUMN Read a logical telemetry column safely.

    if ismember( ...
            variableName, ...
            inputTable.Properties.VariableNames)

        rawValue = ...
            inputTable.(variableName);

        if islogical(rawValue)

            outputColumn = ...
                rawValue(:);

        elseif isnumeric(rawValue)

            outputColumn = ...
                rawValue(:) ~= 0;

        else

            outputColumn = ...
                strcmpi( ...
                    string(rawValue(:)), ...
                    "true");
        end

    else

        outputColumn = ...
            false( ...
                expectedRows, ...
                1);
    end
end


function outputColumn = getStringColumn( ...
    inputTable, variableName, expectedRows, defaultValue)
%GETSTRINGCOLUMN Read a string telemetry column safely.

    if ismember( ...
            variableName, ...
            inputTable.Properties.VariableNames)

        outputColumn = ...
            string( ...
                inputTable.(variableName));

        outputColumn = ...
            outputColumn(:);

    else

        outputColumn = ...
            repmat( ...
                string(defaultValue), ...
                expectedRows, ...
                1);
    end
end


function wrappedDegrees = wrapAngleDegrees(inputDegrees)
%WRAPANGLEDEGREES Wrap degrees into [-180, 180].

    wrappedDegrees = ...
        mod(inputDegrees + 180, 360) - 180;
end


function summaryText = getSummaryText( ...
    summaryData, fieldName, defaultText)
%GETSUMMARYTEXT Retrieve a summary value as display text.

    summaryText = ...
        string(defaultText);

    if istable(summaryData) && ...
            ismember( ...
                fieldName, ...
                summaryData.Properties.VariableNames)

        summaryText = ...
            string( ...
                summaryData.(fieldName)(1));

    elseif isstruct(summaryData) && ...
            isfield(summaryData, fieldName)

        summaryText = ...
            string( ...
                summaryData.(fieldName));
    end

    if summaryText == "1" || ...
            lower(summaryText) == "true"

        summaryText = ...
            "Successful";
    end
end


function metricText = formatSummaryMetric( ...
    summaryData, fieldName, fallbackValue, formatText)
%FORMATSUMMARYMETRIC Retrieve and format one mission metric.

    metricValue = ...
        fallbackValue;

    if istable(summaryData) && ...
            ismember( ...
                fieldName, ...
                summaryData.Properties.VariableNames)

        candidateValue = ...
            summaryData.(fieldName)(1);

        if isnumeric(candidateValue)

            metricValue = ...
                double(candidateValue);
        end

    elseif isstruct(summaryData) && ...
            isfield(summaryData, fieldName)

        candidateValue = ...
            summaryData.(fieldName);

        if isnumeric(candidateValue)

            metricValue = ...
                double(candidateValue);
        end
    end

    if isempty(metricValue) || ...
            ~isfinite(metricValue)

        metricText = ...
            "Not recorded";

    else

        metricText = ...
            string( ...
                sprintf( ...
                    formatText, ...
                    metricValue));
    end
end