function plotOutputs = generateMissionReportPlots(telemetryFile, projectRoot)
%GENERATEMISSIONREPORTPLOTS Create portfolio-ready mission result plots.
%
% Generated files:
%   01_flight_path.png
%   02_speed_and_wind.png
%   03_bird_clearance_and_apf.png
%   04_mapping_and_landing.png
%
% The function is intentionally defensive. A plot failure does not remove
% the CSV, MAT, or MP4 outputs created by the main mission.

    plotOutputs.generated = false;
    plotOutputs.outputDirectory = fullfile( ...
        projectRoot, ...
        "output", ...
        "plots");

    plotOutputs.files = strings(0, 1);

    if ~isfile(telemetryFile)
        warning( ...
            "MissionPlots:TelemetryMissing", ...
            "Telemetry file was not found: %s", ...
            telemetryFile);
        return;
    end

    if ~isfolder(plotOutputs.outputDirectory)
        mkdir(plotOutputs.outputDirectory);
    end

    try
        telemetry = readtable(telemetryFile);

        %% Plot 1: 3D flight path
        figureOne = figure( ...
            "Visible", "off", ...
            "Color", "white", ...
            "Position", [100, 100, 1100, 700]);

        axesOne = axes("Parent", figureOne);

        plot3( ...
            axesOne, ...
            telemetry.PositionXMetres, ...
            telemetry.PositionYMetres, ...
            telemetry.PositionZMetres, ...
            "LineWidth", 1.8);

        hold(axesOne, "on");

        plot3( ...
            axesOne, ...
            telemetry.PositionXMetres(1), ...
            telemetry.PositionYMetres(1), ...
            telemetry.PositionZMetres(1), ...
            "o", ...
            "MarkerSize", 8, ...
            "LineWidth", 1.4);

        plot3( ...
            axesOne, ...
            telemetry.PositionXMetres(end), ...
            telemetry.PositionYMetres(end), ...
            telemetry.PositionZMetres(end), ...
            "p", ...
            "MarkerSize", 11, ...
            "LineWidth", 1.4);

        grid(axesOne, "on");
        xlabel(axesOne, "World X (m)");
        ylabel(axesOne, "World Y (m)");
        zlabel(axesOne, "Altitude (m)");
        title(axesOne, "Autonomous UAV 3D Flight Path");
        legend(axesOne, "Flight path", "Takeoff", "Landing", ...
            "Location", "best");
        view(axesOne, 38, 24);

        flightPathFile = fullfile( ...
            plotOutputs.outputDirectory, ...
            "01_flight_path.png");

        exportgraphics(figureOne, flightPathFile, "Resolution", 180);
        close(figureOne);

        %% Plot 2: ground speed, air speed, and wind
        figureTwo = figure( ...
            "Visible", "off", ...
            "Color", "white", ...
            "Position", [100, 100, 1100, 700]);

        axesTwo = axes("Parent", figureTwo);

        plot( ...
            axesTwo, ...
            telemetry.TimeSeconds, ...
            telemetry.GroundSpeedMetresPerSecond, ...
            "LineWidth", 1.5);

        hold(axesTwo, "on");

        plot( ...
            axesTwo, ...
            telemetry.TimeSeconds, ...
            telemetry.AirSpeedMetresPerSecond, ...
            "LineWidth", 1.5);

        plot( ...
            axesTwo, ...
            telemetry.TimeSeconds, ...
            telemetry.WindSpeedMetresPerSecond, ...
            "LineWidth", 1.3);

        grid(axesTwo, "on");
        xlabel(axesTwo, "Simulation time (s)");
        ylabel(axesTwo, "Speed (m/s)");
        title(axesTwo, "Velocity and Wind-Disturbance History");
        legend(axesTwo, "Ground speed", "Air speed", "Wind speed", ...
            "Location", "best");

        speedFile = fullfile( ...
            plotOutputs.outputDirectory, ...
            "02_speed_and_wind.png");

        exportgraphics(figureTwo, speedFile, "Resolution", 180);
        close(figureTwo);

        %% Plot 3: bird clearance and APF activity
        figureThree = figure( ...
            "Visible", "off", ...
            "Color", "white", ...
            "Position", [100, 100, 1100, 700]);

        axesThree = axes("Parent", figureThree);

        yyaxis(axesThree, "left");
        plot( ...
            axesThree, ...
            telemetry.TimeSeconds, ...
            telemetry.BirdClearanceMetres, ...
            "LineWidth", 1.6);
        ylabel(axesThree, "Drone-to-bird clearance (m)");

        yyaxis(axesThree, "right");
        stairs( ...
            axesThree, ...
            telemetry.TimeSeconds, ...
            double(telemetry.APFAvoidanceActive), ...
            "LineWidth", 1.3);
        ylabel(axesThree, "APF active (0/1)");
        ylim(axesThree, [-0.05, 1.15]);

        grid(axesThree, "on");
        xlabel(axesThree, "Simulation time (s)");
        title(axesThree, "Dynamic Bird Clearance and APF Response");

        birdFile = fullfile( ...
            plotOutputs.outputDirectory, ...
            "03_bird_clearance_and_apf.png");

        exportgraphics(figureThree, birdFile, "Resolution", 180);
        close(figureThree);

        %% Plot 4: occupancy coverage and landing altitude
        figureFour = figure( ...
            "Visible", "off", ...
            "Color", "white", ...
            "Position", [100, 100, 1100, 700]);

        axesFour = axes("Parent", figureFour);

        yyaxis(axesFour, "left");
        plot( ...
            axesFour, ...
            telemetry.TimeSeconds, ...
            telemetry.MapCoveragePercent, ...
            "LineWidth", 1.5);
        ylabel(axesFour, "Map coverage (%)");
        ylim(axesFour, [0, 100]);

        yyaxis(axesFour, "right");
        plot( ...
            axesFour, ...
            telemetry.TimeSeconds, ...
            telemetry.PositionZMetres, ...
            "LineWidth", 1.5);
        ylabel(axesFour, "Altitude (m)");

        grid(axesFour, "on");
        xlabel(axesFour, "Simulation time (s)");
        title(axesFour, "Occupancy Mapping and Landing Profile");

        mappingFile = fullfile( ...
            plotOutputs.outputDirectory, ...
            "04_mapping_and_landing.png");

        exportgraphics(figureFour, mappingFile, "Resolution", 180);
        close(figureFour);

        plotOutputs.files = [ ...
            string(flightPathFile); ...
            string(speedFile); ...
            string(birdFile); ...
            string(mappingFile) ...
        ];

        plotOutputs.generated = true;

    catch plotError
        warning( ...
            "MissionPlots:GenerationFailed", ...
            "Performance plots could not be generated: %s", ...
            plotError.message);

        close all force;
    end
end
