function graphics = drawDrone(ax, drone, config)
%DRAWDRONE Create a simple 3D quadcopter model.
%
% The drone is created inside an hgtransform object. Updating the
% transformation matrix moves and rotates the complete drone model.

    graphics.transform = hgtransform("Parent", ax);

    armLength = 0.60;
    bodyRadius = 0.18;
    rotorRadius = 0.16;

    %% Central body
    [sphereX, sphereY, sphereZ] = sphere(14);

    graphics.body = surf( ...
        sphereX * bodyRadius, ...
        sphereY * bodyRadius, ...
        sphereZ * bodyRadius * 0.55, ...
        "Parent", graphics.transform, ...
        "FaceColor", [0.12, 0.15, 0.18], ...
        "EdgeColor", "none");

    %% Drone arms
    graphics.arm1 = line( ...
        "Parent", graphics.transform, ...
        "XData", [-armLength, armLength], ...
        "YData", [-armLength, armLength], ...
        "ZData", [0, 0], ...
        "Color", [0.25, 0.25, 0.28], ...
        "LineWidth", 6);

    graphics.arm2 = line( ...
        "Parent", graphics.transform, ...
        "XData", [-armLength, armLength], ...
        "YData", [armLength, -armLength], ...
        "ZData", [0, 0], ...
        "Color", [0.25, 0.25, 0.28], ...
        "LineWidth", 6);

    %% Rotor locations
    rotorCenters = [
         armLength,  armLength, 0
         armLength, -armLength, 0
        -armLength,  armLength, 0
        -armLength, -armLength, 0
    ];

    rotorAngle = linspace(0, 2*pi, 40);

    graphics.rotors = gobjects(4, 1);

    for i = 1:4
        rotorX = rotorCenters(i,1) + rotorRadius*cos(rotorAngle);
        rotorY = rotorCenters(i,2) + rotorRadius*sin(rotorAngle);
        rotorZ = rotorCenters(i,3) + zeros(size(rotorAngle));

        graphics.rotors(i) = line( ...
            "Parent", graphics.transform, ...
            "XData", rotorX, ...
            "YData", rotorY, ...
            "ZData", rotorZ, ...
            "Color", [0.10, 0.10, 0.10], ...
            "LineWidth", 2);
    end

    %% Front orientation marker
    graphics.frontMarker = line( ...
        "Parent", graphics.transform, ...
        "XData", [0, 0.85], ...
        "YData", [0, 0], ...
        "ZData", [0.03, 0.03], ...
        "Color", [0.95, 0.15, 0.10], ...
        "LineWidth", 4);

    %% Front lights
    graphics.frontLight1 = line( ...
        "Parent", graphics.transform, ...
        "XData", armLength, ...
        "YData", armLength, ...
        "ZData", 0.05, ...
        "Marker", "o", ...
        "MarkerSize", 7, ...
        "MarkerFaceColor", [0.95, 0.15, 0.10], ...
        "MarkerEdgeColor", "none");

    graphics.frontLight2 = line( ...
        "Parent", graphics.transform, ...
        "XData", armLength, ...
        "YData", -armLength, ...
        "ZData", 0.05, ...
        "Marker", "o", ...
        "MarkerSize", 7, ...
        "MarkerFaceColor", [0.95, 0.15, 0.10], ...
        "MarkerEdgeColor", "none");

    %% Rear lights
    graphics.rearLight1 = line( ...
        "Parent", graphics.transform, ...
        "XData", -armLength, ...
        "YData", armLength, ...
        "ZData", 0.05, ...
        "Marker", "o", ...
        "MarkerSize", 7, ...
        "MarkerFaceColor", [0.10, 0.85, 0.25], ...
        "MarkerEdgeColor", "none");

    graphics.rearLight2 = line( ...
        "Parent", graphics.transform, ...
        "XData", -armLength, ...
        "YData", -armLength, ...
        "ZData", 0.05, ...
        "Marker", "o", ...
        "MarkerSize", 7, ...
        "MarkerFaceColor", [0.10, 0.85, 0.25], ...
        "MarkerEdgeColor", "none");

    %% Set initial drone position
    translationMatrix = makehgtform("translate", drone.position);
    rotationMatrix = makehgtform("zrotate", drone.yaw);

    graphics.transform.Matrix = translationMatrix * rotationMatrix;

    graphics.scale = config.drone.radius;
end