function updateDroneGraphics(graphics, drone)
%UPDATEDRONEGRAPHICS Move and rotate the displayed drone.

    translationMatrix = makehgtform( ...
        "translate", drone.position);

    yawRotation = makehgtform( ...
        "zrotate", drone.yaw);

    pitchRotation = makehgtform( ...
        "yrotate", drone.pitch);

    rollRotation = makehgtform( ...
        "xrotate", drone.roll);

    graphics.transform.Matrix = ...
        translationMatrix * ...
        yawRotation * ...
        pitchRotation * ...
        rollRotation;
end