function drone = updateDroneDynamics( ...
    drone, desiredGroundVelocity, wind, config)
%UPDATEDRONEDYNAMICS Update drone motion and orientation.
%
% Translational model:
%
%   desired air velocity =
%       desired ground velocity + wind compensation
%
%   ground velocity =
%       air velocity + wind velocity
%
% Yaw behavior:
%
%   Normal flight:
%       Yaw follows horizontal ground motion only when the speed is large
%       enough to produce a reliable heading.
%
%   Landing:
%       Yaw follows drone.commandedYaw using a rate-limited controller.
%
% This prevents small wind and position-correction velocities from
% producing rapid heading reversals during landing.

    dt = config.timeStep;

    %% Requested air-relative velocity
    desiredAirVelocity = ...
        desiredGroundVelocity + ...
        wind.compensationVelocity;

    %% Requested air-relative acceleration
    velocityError = ...
        desiredAirVelocity - ...
        drone.airVelocity;

    requestedAcceleration = ...
        velocityError / ...
        config.drone.velocityResponseTime;

    %% Limit acceleration
    accelerationMagnitude = ...
        norm(requestedAcceleration);

    if accelerationMagnitude > ...
            config.drone.maxAcceleration

        requestedAcceleration = ...
            requestedAcceleration / ...
            accelerationMagnitude * ...
            config.drone.maxAcceleration;
    end

    drone.acceleration = ...
        requestedAcceleration;

    %% Update air-relative velocity
    drone.airVelocity = ...
        drone.airVelocity + ...
        drone.acceleration * dt;

    %% Limit air-relative speed
    airSpeed = ...
        norm(drone.airVelocity);

    if airSpeed > config.drone.maxSpeed

        drone.airVelocity = ...
            drone.airVelocity / ...
            airSpeed * ...
            config.drone.maxSpeed;
    end

    %% Atmospheric disturbance
    drone.windVelocity = ...
        wind.totalVelocity;

    %% Ground-relative velocity
    drone.velocity = ...
        drone.airVelocity + ...
        drone.windVelocity;

    %% Update position
    drone.previousPosition = ...
        drone.position;

    drone.position = ...
        drone.position + ...
        drone.velocity * dt;

    %% World boundaries
    drone.position(1) = min( ...
        config.world.xLimits(2), ...
        max( ...
            config.world.xLimits(1), ...
            drone.position(1)));

    drone.position(2) = min( ...
        config.world.yLimits(2), ...
        max( ...
            config.world.yLimits(1), ...
            drone.position(2)));

    if drone.position(3) < 0

        drone.position(3) = 0;

        if drone.velocity(3) < 0
            drone.velocity(3) = 0;
        end

        if drone.airVelocity(3) < 0
            drone.airVelocity(3) = 0;
        end
    end

    drone.position(3) = min( ...
        config.world.zLimits(2), ...
        drone.position(3));

    %% Distance travelled
    movementDistance = ...
        norm( ...
            drone.position - ...
            drone.previousPosition);

    drone.distanceTravelled = ...
        drone.distanceTravelled + ...
        movementDistance;

    %% Yaw update
    if drone.yawControlActive

        % Explicit yaw control is used during landing.
        yawError = wrapAngleToPiLocal( ...
            drone.commandedYaw - drone.yaw);

        desiredYawRate = ...
            config.landing.yawGain * yawError;

        desiredYawRate = max( ...
            -config.landing.maximumYawRate, ...
            min( ...
                config.landing.maximumYawRate, ...
                desiredYawRate));

        yawStep = ...
            desiredYawRate * dt;

        % Prevent the integration step from overshooting the target.
        if abs(yawStep) > abs(yawError)
            yawStep = yawError;
        end

        drone.yaw = ...
            wrapAngleToPiLocal( ...
                drone.yaw + yawStep);

        drone.yawError = ...
            wrapAngleToPiLocal( ...
                drone.commandedYaw - drone.yaw);

        drone.commandedYawRate = ...
            desiredYawRate;

    else

        % During ordinary flight, update heading only when the horizontal
        % velocity is large enough to be reliable.
        horizontalGroundSpeed = ...
            norm(drone.velocity(1:2));

        if horizontalGroundSpeed >= ...
                config.drone.minimumYawUpdateSpeed

            desiredNavigationYaw = ...
                atan2( ...
                    drone.velocity(2), ...
                    drone.velocity(1));

            navigationYawError = ...
                wrapAngleToPiLocal( ...
                    desiredNavigationYaw - ...
                    drone.yaw);

            maximumYawStep = ...
                config.drone.maximumNavigationYawRate * dt;

            navigationYawStep = max( ...
                -maximumYawStep, ...
                min( ...
                    maximumYawStep, ...
                    navigationYawError));

            drone.yaw = ...
                wrapAngleToPiLocal( ...
                    drone.yaw + navigationYawStep);

            drone.commandedYaw = ...
                desiredNavigationYaw;

            drone.yawError = ...
                wrapAngleToPiLocal( ...
                    desiredNavigationYaw - ...
                    drone.yaw);

            drone.commandedYawRate = ...
                navigationYawStep / dt;

        else

            % Hold the previous yaw when motion is too small.
            drone.commandedYaw = ...
                drone.yaw;

            drone.yawError = 0;
            drone.commandedYawRate = 0;
        end
    end

    %% Approximate pitch and roll
    desiredPitch = ...
        -0.12 * drone.acceleration(1);

    desiredRoll = ...
        0.12 * drone.acceleration(2);

    maximumTilt = ...
        deg2rad(18);

    drone.pitch = max( ...
        -maximumTilt, ...
        min(maximumTilt, desiredPitch));

    drone.roll = max( ...
        -maximumTilt, ...
        min(maximumTilt, desiredRoll));
end


function wrappedAngle = wrapAngleToPiLocal(inputAngle)
%WRAPANGLETOPILOCAL Wrap an angle into the interval [-pi, pi].

    wrappedAngle = ...
        mod(inputAngle + pi, 2*pi) - pi;
end