function outputs = finalizeMissionRecorder( ...
    recorder, ...
    summary, ...
    config, ...
    drone, ...
    bird, ...
    wind, ...
    occupancyGrid)
%FINALIZEMISSIONRECORDER Close video and save CSV/MAT outputs.
%
% This function:
%   1. Closes the VideoWriter object
%   2. Verifies that every telemetry column has the same row count
%   3. Creates the telemetry table
%   4. Writes telemetry and summary CSV files
%   5. Saves the complete MATLAB mission dataset
%
% The telemetry normalization step prevents table-construction failures
% if one recorded field contains fewer or more samples than the others.

    %% Initialize output status
    outputs.telemetryFile = recorder.telemetryFile;
    outputs.summaryFile = recorder.summaryFile;
    outputs.matFile = recorder.matFile;
    outputs.videoFile = recorder.videoFile;

    outputs.telemetrySaved = false;
    outputs.summarySaved = false;
    outputs.matSaved = false;
    outputs.videoSaved = false;

    %% Close and finalize the video
    if ~isempty(recorder.videoWriter)

        try
            close(recorder.videoWriter);

            outputs.videoSaved = ...
                isfile(recorder.videoFile);

        catch videoCloseError

            warning( ...
                "MissionRecorder:VideoCloseFailed", ...
                "The video could not be closed correctly: %s", ...
                videoCloseError.message);
        end
    end

    %% Determine expected telemetry row count
    expectedRowCount = ...
        recorder.loggedSampleCount;

    if expectedRowCount <= 0

        warning( ...
            "MissionRecorder:NoTelemetrySamples", ...
            "No telemetry samples were recorded.");

        expectedRowCount = 0;
    end

    %% Normalize every telemetry field
    telemetryData = recorder.data;

    telemetryFieldNames = ...
        fieldnames(telemetryData);

    for fieldIndex = 1:numel(telemetryFieldNames)

        fieldName = ...
            telemetryFieldNames{fieldIndex};

        fieldValue = ...
            telemetryData.(fieldName);

        telemetryData.(fieldName) = ...
            normalizeTelemetryColumn( ...
                fieldValue, ...
                expectedRowCount, ...
                fieldName);
    end

    %% Verify final telemetry field sizes
    for fieldIndex = 1:numel(telemetryFieldNames)

        fieldName = ...
            telemetryFieldNames{fieldIndex};

        fieldRowCount = ...
            size(telemetryData.(fieldName), 1);

        if fieldRowCount ~= expectedRowCount

            error( ...
                "MissionRecorder:TelemetryLengthMismatch", ...
                [ ...
                    "Telemetry field '%s' contains %d rows, " ...
                    "but %d rows were expected." ...
                ], ...
                fieldName, ...
                fieldRowCount, ...
                expectedRowCount);
        end
    end

    %% Create telemetry table
    telemetryTable = table( ...
        telemetryData.Time, ...
        telemetryData.MissionState, ...
        telemetryData.WaypointIndex, ...
        telemetryData.PositionX, ...
        telemetryData.PositionY, ...
        telemetryData.PositionZ, ...
        telemetryData.GroundVelocityX, ...
        telemetryData.GroundVelocityY, ...
        telemetryData.GroundVelocityZ, ...
        telemetryData.GroundSpeed, ...
        telemetryData.AirVelocityX, ...
        telemetryData.AirVelocityY, ...
        telemetryData.AirVelocityZ, ...
        telemetryData.AirSpeed, ...
        telemetryData.YawDegrees, ...
        telemetryData.PitchDegrees, ...
        telemetryData.RollDegrees, ...
        telemetryData.TargetDistance, ...
        telemetryData.DistanceTravelled, ...
        telemetryData.WindX, ...
        telemetryData.WindY, ...
        telemetryData.WindZ, ...
        telemetryData.WindSpeed, ...
        telemetryData.BirdActive, ...
        telemetryData.BirdPositionX, ...
        telemetryData.BirdPositionY, ...
        telemetryData.BirdPositionZ, ...
        telemetryData.BirdDistance, ...
        telemetryData.BirdClearance, ...
        telemetryData.BirdLidarHits, ...
        telemetryData.APFAvoidanceActive, ...
        telemetryData.APFEmergencyActive, ...
        telemetryData.APFObstacleCount, ...
        telemetryData.RepulsiveSpeed, ...
        telemetryData.TangentialSpeed, ...
        telemetryData.MapCoveragePercent, ...
        telemetryData.MapFreeCells, ...
        telemetryData.MapOccupiedCells, ...
        telemetryData.MapUpdateCount, ...
        telemetryData.FPVTargetVisible, ...
        telemetryData.FPVBirdVisible, ...
        telemetryData.FPVForwardObstacleDistance, ...
        'VariableNames', { ...
            'TimeSeconds', ...
            'MissionState', ...
            'WaypointIndex', ...
            'PositionXMetres', ...
            'PositionYMetres', ...
            'PositionZMetres', ...
            'GroundVelocityXMetresPerSecond', ...
            'GroundVelocityYMetresPerSecond', ...
            'GroundVelocityZMetresPerSecond', ...
            'GroundSpeedMetresPerSecond', ...
            'AirVelocityXMetresPerSecond', ...
            'AirVelocityYMetresPerSecond', ...
            'AirVelocityZMetresPerSecond', ...
            'AirSpeedMetresPerSecond', ...
            'YawDegrees', ...
            'PitchDegrees', ...
            'RollDegrees', ...
            'TargetDistanceMetres', ...
            'DistanceTravelledMetres', ...
            'WindXMetresPerSecond', ...
            'WindYMetresPerSecond', ...
            'WindZMetresPerSecond', ...
            'WindSpeedMetresPerSecond', ...
            'BirdActive', ...
            'BirdPositionXMetres', ...
            'BirdPositionYMetres', ...
            'BirdPositionZMetres', ...
            'BirdDistanceMetres', ...
            'BirdClearanceMetres', ...
            'BirdLidarHits', ...
            'APFAvoidanceActive', ...
            'APFEmergencyActive', ...
            'APFObstacleCount', ...
            'RepulsiveSpeedMetresPerSecond', ...
            'TangentialSpeedMetresPerSecond', ...
            'MapCoveragePercent', ...
            'MapFreeCells', ...
            'MapOccupiedCells', ...
            'MapUpdateCount', ...
            'FPVTargetVisible', ...
            'FPVBirdVisible', ...
            'FPVForwardObstacleDistanceMetres' ...
        });

    %% Save telemetry CSV
    if config.logging.enabled

        try
            writetable( ...
                telemetryTable, ...
                recorder.telemetryFile);

            outputs.telemetrySaved = true;

        catch telemetryError

            warning( ...
                "MissionRecorder:TelemetrySaveFailed", ...
                "Telemetry CSV could not be saved: %s", ...
                telemetryError.message);
        end
    end

    %% Prepare summary values
    missionCompletedText = ...
        string(summary.MissionCompleted);

    minimumBirdClearance = ...
        summary.MinimumBirdClearanceMetres;

    if ~isfinite(minimumBirdClearance)
        minimumBirdClearance = NaN;
    end

    %% Create summary table
    summaryTable = table( ...
        missionCompletedText, ...
        summary.SimulationTimeSeconds, ...
        summary.DistanceTravelledMetres, ...
        summary.MaximumWindSpeedMetresPerSecond, ...
        summary.AverageWindSpeedMetresPerSecond, ...
        summary.MaximumLateralDeviationMetres, ...
        summary.AverageLateralDeviationMetres, ...
        summary.TotalAPFActivationSteps, ...
        summary.BirdAvoidanceActivationSteps, ...
        minimumBirdClearance, ...
        summary.FPVBirdVisibleFrames, ...
        summary.OccupancyCoveragePercent, ...
        summary.OccupancyMapUpdates, ...
        recorder.loggedSampleCount, ...
        recorder.videoFrameCount, ...
        'VariableNames', { ...
            'MissionCompleted', ...
            'SimulationTimeSeconds', ...
            'DistanceTravelledMetres', ...
            'MaximumWindSpeedMetresPerSecond', ...
            'AverageWindSpeedMetresPerSecond', ...
            'MaximumLateralDeviationMetres', ...
            'AverageLateralDeviationMetres', ...
            'TotalAPFActivationSteps', ...
            'BirdAvoidanceActivationSteps', ...
            'MinimumBirdClearanceMetres', ...
            'FPVBirdVisibleFrames', ...
            'OccupancyCoveragePercent', ...
            'OccupancyMapUpdates', ...
            'TelemetrySamples', ...
            'VideoFrames' ...
        });

    %% Save summary CSV
    try
        writetable( ...
            summaryTable, ...
            recorder.summaryFile);

        outputs.summarySaved = true;

    catch summaryError

        warning( ...
            "MissionRecorder:SummarySaveFailed", ...
            "Mission summary CSV could not be saved: %s", ...
            summaryError.message);
    end

    %% Save complete MATLAB dataset
    try
        save( ...
            recorder.matFile, ...
            "telemetryTable", ...
            "summaryTable", ...
            "summary", ...
            "config", ...
            "drone", ...
            "bird", ...
            "wind", ...
            "occupancyGrid", ...
            "-v7.3");

        outputs.matSaved = true;

    catch matError

        warning( ...
            "MissionRecorder:MatSaveFailed", ...
            "MAT mission data could not be saved: %s", ...
            matError.message);
    end
end


function normalizedColumn = normalizeTelemetryColumn( ...
    inputColumn, expectedRowCount, fieldName)
%NORMALIZETELEMETRYCOLUMN Make one telemetry field a column of fixed size.
%
% The function:
%   - Converts row vectors into column vectors
%   - Truncates accidental extra samples
%   - Pads missing numeric values with NaN
%   - Pads missing logical values with false
%   - Pads missing string values with missing strings

    %% Convert input into a column
    normalizedColumn = ...
        inputColumn(:);

    currentRowCount = ...
        size(normalizedColumn, 1);

    %% Column already has the correct length
    if currentRowCount == expectedRowCount
        return;
    end

    %% Truncate accidental extra rows
    if currentRowCount > expectedRowCount

        warning( ...
            "MissionRecorder:ExtraTelemetryRows", ...
            [ ...
                "Telemetry field '%s' contained %d rows. " ...
                "It was truncated to %d rows." ...
            ], ...
            fieldName, ...
            currentRowCount, ...
            expectedRowCount);

        normalizedColumn = ...
            normalizedColumn(1:expectedRowCount);

        return;
    end

    %% Calculate number of missing rows
    missingRowCount = ...
        expectedRowCount - currentRowCount;

    warning( ...
        "MissionRecorder:MissingTelemetryRows", ...
        [ ...
            "Telemetry field '%s' contained %d rows. " ...
            "%d missing rows were padded." ...
        ], ...
        fieldName, ...
        currentRowCount, ...
        missingRowCount);

    %% Create padding with a matching data type
    if isstring(normalizedColumn)

        paddingValues = ...
            strings(missingRowCount, 1);

        paddingValues(:) = missing;

    elseif islogical(normalizedColumn)

        paddingValues = ...
            false(missingRowCount, 1);

    elseif isnumeric(normalizedColumn)

        paddingValues = ...
            NaN(missingRowCount, 1, ...
            "like", normalizedColumn);

    elseif iscategorical(normalizedColumn)

        paddingValues = ...
            categorical( ...
                strings(missingRowCount, 1));

    else

        error( ...
            "MissionRecorder:UnsupportedTelemetryType", ...
            [ ...
                "Telemetry field '%s' has unsupported " ...
                "data type '%s'." ...
            ], ...
            fieldName, ...
            class(normalizedColumn));
    end

    %% Append padding
    normalizedColumn = [
        normalizedColumn
        paddingValues
    ];
end