function recorder = recordMissionStep( ...
    recorder, ...
    mainFigure, ...
    simulationTime, ...
    drone, ...
    bird, ...
    wind, ...
    avoidance, ...
    lidar, ...
    occupancyGrid, ...
    fpv, ...
    targetPosition, ...
    config)
%RECORDMISSIONSTEP Log telemetry and capture a dashboard video frame.

    timeTolerance = 1e-9;

    %% Telemetry logging
    if recorder.loggingEnabled && ...
            simulationTime + timeTolerance >= ...
            recorder.nextLogTime

        birdDistance = ...
            norm(drone.position - bird.position);

        if bird.active

            birdClearance = ...
                birdDistance - ...
                drone.radius - ...
                bird.radius;

        else

            birdClearance = NaN;
        end

        birdLidarHits = ...
            sum(lidar.hitSource == 2);

        if isfinite(fpv.nearestForwardObstacle)

            forwardObstacleDistance = ...
                fpv.nearestForwardObstacle;

        else

            forwardObstacleDistance = NaN;
        end

        sampleIndex = ...
            recorder.loggedSampleCount + 1;

        recorder.data.Time(sampleIndex,1) = ...
            simulationTime;

        recorder.data.MissionState(sampleIndex,1) = ...
            string(drone.missionState);

        recorder.data.WaypointIndex(sampleIndex,1) = ...
            drone.currentWaypointIndex;

        recorder.data.PositionX(sampleIndex,1) = ...
            drone.position(1);

        recorder.data.PositionY(sampleIndex,1) = ...
            drone.position(2);

        recorder.data.PositionZ(sampleIndex,1) = ...
            drone.position(3);

        recorder.data.GroundVelocityX(sampleIndex,1) = ...
            drone.velocity(1);

        recorder.data.GroundVelocityY(sampleIndex,1) = ...
            drone.velocity(2);

        recorder.data.GroundVelocityZ(sampleIndex,1) = ...
            drone.velocity(3);

        recorder.data.GroundSpeed(sampleIndex,1) = ...
            norm(drone.velocity);

        recorder.data.AirVelocityX(sampleIndex,1) = ...
            drone.airVelocity(1);

        recorder.data.AirVelocityY(sampleIndex,1) = ...
            drone.airVelocity(2);

        recorder.data.AirVelocityZ(sampleIndex,1) = ...
            drone.airVelocity(3);

        recorder.data.AirSpeed(sampleIndex,1) = ...
            norm(drone.airVelocity);

        recorder.data.YawDegrees(sampleIndex,1) = ...
            rad2deg(drone.yaw);

        recorder.data.PitchDegrees(sampleIndex,1) = ...
            rad2deg(drone.pitch);

        recorder.data.RollDegrees(sampleIndex,1) = ...
            rad2deg(drone.roll);

        recorder.data.TargetDistance(sampleIndex,1) = ...
            norm(targetPosition - drone.position);

        recorder.data.DistanceTravelled(sampleIndex,1) = ...
            drone.distanceTravelled;

        recorder.data.WindX(sampleIndex,1) = ...
            wind.totalVelocity(1);

        recorder.data.WindY(sampleIndex,1) = ...
            wind.totalVelocity(2);

        recorder.data.WindZ(sampleIndex,1) = ...
            wind.totalVelocity(3);

        recorder.data.WindSpeed(sampleIndex,1) = ...
            wind.speed;

        recorder.data.BirdActive(sampleIndex,1) = ...
            bird.active;

        recorder.data.BirdPositionX(sampleIndex,1) = ...
            bird.position(1);

        recorder.data.BirdPositionY(sampleIndex,1) = ...
            bird.position(2);

        recorder.data.BirdPositionZ(sampleIndex,1) = ...
            bird.position(3);

        recorder.data.BirdDistance(sampleIndex,1) = ...
            birdDistance;

        recorder.data.BirdClearance(sampleIndex,1) = ...
            birdClearance;

        recorder.data.BirdLidarHits(sampleIndex,1) = ...
            birdLidarHits;

        recorder.data.APFAvoidanceActive(sampleIndex,1) = ...
            avoidance.active;

        recorder.data.APFEmergencyActive(sampleIndex,1) = ...
            avoidance.emergencyActive;

        recorder.data.APFObstacleCount(sampleIndex,1) = ...
            avoidance.obstacleCount;

        recorder.data.RepulsiveSpeed(sampleIndex,1) = ...
            norm(avoidance.repulsiveVelocity);

        recorder.data.TangentialSpeed(sampleIndex,1) = ...
            norm(avoidance.tangentialVelocity);

        recorder.data.MapCoveragePercent(sampleIndex,1) = ...
            occupancyGrid.coveragePercent;

        recorder.data.MapFreeCells(sampleIndex,1) = ...
            occupancyGrid.freeCellCount;

        recorder.data.MapOccupiedCells(sampleIndex,1) = ...
            occupancyGrid.occupiedCellCount;

        recorder.data.MapUpdateCount(sampleIndex,1) = ...
            occupancyGrid.updateCount;

        recorder.data.FPVTargetVisible(sampleIndex,1) = ...
            fpv.targetVisible;

        recorder.data.FPVBirdVisible(sampleIndex,1) = ...
            fpv.birdVisible;

        recorder.data.FPVForwardObstacleDistance(sampleIndex,1) = ...
            forwardObstacleDistance;

        recorder.loggedSampleCount = sampleIndex;

        recorder.nextLogTime = ...
            recorder.nextLogTime + ...
            config.logging.sampleInterval;
    end

    %% Dashboard video capture
    if recorder.videoEnabled && ...
            simulationTime + timeTolerance >= ...
            recorder.nextVideoTime

        try
            frame = getframe(mainFigure);

            writeVideo( ...
                recorder.videoWriter, ...
                frame);

            recorder.videoFrameCount = ...
                recorder.videoFrameCount + 1;

            recorder.nextVideoTime = ...
                recorder.nextVideoTime + ...
                config.video.captureInterval;

        catch videoError

            recorder.videoEnabled = false;

            recorder.videoFailureMessage = ...
                string(videoError.message);

            warning( ...
                "MissionRecorder:VideoCaptureFailed", ...
                "Video capture was stopped: %s", ...
                videoError.message);
        end
    end
end