function environment = createUrbanEnvironment(ax, config)
%CREATEURBANENVIRONMENT Draw the static urban mission environment.
%
% The dynamic bird is created separately and is not included in the
% static building arrays.

    hold(ax, "on");

    %% Ground
    groundX = [
        config.world.xLimits(1)
        config.world.xLimits(2)
        config.world.xLimits(2)
        config.world.xLimits(1)
    ];

    groundY = [
        config.world.yLimits(1)
        config.world.yLimits(1)
        config.world.yLimits(2)
        config.world.yLimits(2)
    ];

    groundZ = zeros(4, 1);

    patch( ...
        ax, ...
        groundX, ...
        groundY, ...
        groundZ, ...
        [0.68, 0.71, 0.69], ...
        "EdgeColor", "none");

    %% Road
    roadWidth = 3.5;

    patch( ...
        ax, ...
        [0, 30, 30, 0], ...
        [ ...
            -roadWidth/2, ...
            -roadWidth/2, ...
             roadWidth/2, ...
             roadWidth/2 ...
        ], ...
        [0.01, 0.01, 0.01, 0.01], ...
        [0.18, 0.19, 0.22], ...
        "EdgeColor", "none");

    %% Road markings
    for xPosition = 1:3:29

        plot3( ...
            ax, ...
            [xPosition, xPosition + 1.4], ...
            [0, 0], ...
            [0.025, 0.025], ...
            "-", ...
            "Color", [0.95, 0.85, 0.20], ...
            "LineWidth", 2);
    end

    %% Static side buildings
    buildingCenters = [
         5.5,  3.6
         7.8, -3.6
        16.5,  3.6
        19.0, -3.6
        24.0,  3.6
        26.0, -3.6
    ];

    buildingDimensions = [
        2.0, 2.2, 4.8
        2.2, 2.3, 4.0
        2.1, 2.4, 5.4
        2.2, 2.3, 4.5
        2.0, 2.4, 5.2
        2.1, 2.2, 4.2
    ];

    buildingColors = [
        0.68, 0.40, 0.23
        0.34, 0.53, 0.72
        0.70, 0.43, 0.24
        0.37, 0.55, 0.73
        0.67, 0.39, 0.22
        0.35, 0.51, 0.69
    ];

    numberOfBuildings = size(buildingCenters, 1);

    buildingHandles = gobjects(numberOfBuildings, 1);

    for buildingIndex = 1:numberOfBuildings

        buildingHandles(buildingIndex) = drawBuilding( ...
            ax, ...
            buildingCenters(buildingIndex, :), ...
            buildingDimensions(buildingIndex, :), ...
            buildingColors(buildingIndex, :));
    end

    %% Takeoff marker
    startPosition = config.drone.startPosition;

    plot3( ...
        ax, ...
        startPosition(1), ...
        startPosition(2), ...
        0.08, ...
        "o", ...
        "MarkerSize", 14, ...
        "MarkerFaceColor", [0.10, 0.75, 0.25], ...
        "MarkerEdgeColor", "black");

    text( ...
        ax, ...
        startPosition(1), ...
        startPosition(2), ...
        0.35, ...
        "TAKEOFF", ...
        "Color", [0.95, 0.95, 0.95], ...
        "HorizontalAlignment", "center", ...
        "FontWeight", "bold");

    %% Landing marker
    goalPosition = config.mission.goalPosition;

    plot3( ...
        ax, ...
        goalPosition(1), ...
        goalPosition(2), ...
        0.08, ...
        "o", ...
        "MarkerSize", 14, ...
        "MarkerFaceColor", [0.90, 0.20, 0.15], ...
        "MarkerEdgeColor", "black");

    text( ...
        ax, ...
        goalPosition(1), ...
        goalPosition(2), ...
        0.35, ...
        "LAND", ...
        "Color", [0.95, 0.95, 0.95], ...
        "HorizontalAlignment", "center", ...
        "FontWeight", "bold");

    %% Planned mission route
    waypoints = config.mission.waypoints;

    plot3( ...
        ax, ...
        waypoints(:,1), ...
        waypoints(:,2), ...
        waypoints(:,3), ...
        "--", ...
        "Color", [0.20, 0.90, 1.00], ...
        "LineWidth", 1.5);

    scatter3( ...
        ax, ...
        waypoints(:,1), ...
        waypoints(:,2), ...
        waypoints(:,3), ...
        38, ...
        [1.00, 0.30, 0.75], ...
        "filled");

    %% Bird crossing path
    if config.bird.enabled

        birdStart = config.bird.startPosition;
        birdEnd = config.bird.endPosition;

        plot3( ...
            ax, ...
            [birdStart(1), birdEnd(1)], ...
            [birdStart(2), birdEnd(2)], ...
            [birdStart(3), birdEnd(3)], ...
            ":", ...
            "Color", [1.00, 0.55, 0.15], ...
            "LineWidth", 1.5);

        plot3( ...
            ax, ...
            birdStart(1), ...
            birdStart(2), ...
            birdStart(3), ...
            "o", ...
            "MarkerSize", 8, ...
            "MarkerFaceColor", [1.00, 0.55, 0.15], ...
            "MarkerEdgeColor", "black");

        text( ...
            ax, ...
            birdStart(1), ...
            birdStart(2), ...
            birdStart(3) + 0.45, ...
            "BIRD START", ...
            "Color", [1.00, 0.70, 0.25], ...
            "FontSize", 8, ...
            "HorizontalAlignment", "center");

        plot3( ...
            ax, ...
            birdEnd(1), ...
            birdEnd(2), ...
            birdEnd(3), ...
            "o", ...
            "MarkerSize", 8, ...
            "MarkerFaceColor", [1.00, 0.55, 0.15], ...
            "MarkerEdgeColor", "black");

        text( ...
            ax, ...
            birdEnd(1), ...
            birdEnd(2), ...
            birdEnd(3) + 0.45, ...
            "BIRD END", ...
            "Color", [1.00, 0.70, 0.25], ...
            "FontSize", 8, ...
            "HorizontalAlignment", "center");
    end

    %% Store static collision information
    environment.buildingCenters = buildingCenters;
    environment.buildingDimensions = buildingDimensions;
    environment.buildingHandles = buildingHandles;
    environment.roadWidth = roadWidth;

    %% Configure axes
    axis(ax, "equal");

    xlim(ax, config.world.xLimits);
    ylim(ax, config.world.yLimits);
    zlim(ax, config.world.zLimits);

    xlabel(ax, "X Position (m)");
    ylabel(ax, "Y Position (m)");
    zlabel(ax, "Altitude (m)");

    title( ...
        ax, ...
        "Autonomous UAV Dynamic Bird Avoidance Test");

    grid(ax, "on");
    box(ax, "on");

    view(ax, 40, 25);
end