function graphics = initializeLidarGraphics( ...
    mainAxes, mainFigure, config)
%INITIALIZELIDARGRAPHICS Create LiDAR visualization objects.
%
% This function creates:
%   1. LiDAR hit points in the main 3D environment
%   2. Selected LiDAR rays in the main 3D environment
%   3. A local top-down LiDAR display
%   4. A circular maximum-range boundary

    %% Create LiDAR hit points in the main 3D view
    graphics.hitPoints3D = scatter3( ...
        mainAxes, ...
        NaN, ...
        NaN, ...
        NaN, ...
        18, ...
        "filled", ...
        "MarkerFaceColor", [1.00, 0.25, 0.10], ...
        "MarkerEdgeColor", "none");

    %% Create LiDAR ray lines in the main 3D view
    graphics.rayLines = line( ...
        mainAxes, ...
        NaN, ...
        NaN, ...
        NaN, ...
        "Color", [0.20, 0.85, 1.00], ...
        "LineWidth", 0.45);

    %% Create local LiDAR axes
    graphics.topAxes = axes( ...
        "Parent", mainFigure, ...
        "Position", [0.77, 0.07, 0.21, 0.36], ...
        "Color", [0.08, 0.09, 0.11]);

    hold(graphics.topAxes, "on");

    axis(graphics.topAxes, "equal");
    grid(graphics.topAxes, "on");
    box(graphics.topAxes, "on");

    %% Configure LiDAR axes appearance
    graphics.topAxes.XColor = [0.90, 0.90, 0.90];
    graphics.topAxes.YColor = [0.90, 0.90, 0.90];

    graphics.topAxes.GridColor = [0.40, 0.40, 0.40];
    graphics.topAxes.GridAlpha = 0.35;

    graphics.topAxes.FontSize = 9;

    lidarRange = config.lidar.maxRange;

    xlim( ...
        graphics.topAxes, ...
        [-lidarRange, lidarRange]);

    ylim( ...
        graphics.topAxes, ...
        [-lidarRange, lidarRange]);

    xlabel( ...
        graphics.topAxes, ...
        "Relative X (m)");

    ylabel( ...
        graphics.topAxes, ...
        "Relative Y (m)");

    title( ...
        graphics.topAxes, ...
        "LIVE 360° LIDAR", ...
        "Color", [0.90, 0.95, 1.00], ...
        "FontWeight", "bold", ...
        "FontSize", 10);

    %% Draw maximum LiDAR range circle
    graphics.rangeCircle = rectangle( ...
        graphics.topAxes, ...
        "Position", [ ...
            -lidarRange, ...
            -lidarRange, ...
            2 * lidarRange, ...
            2 * lidarRange], ...
        "Curvature", [1, 1], ...
        "EdgeColor", [0.55, 0.55, 0.55], ...
        "LineStyle", "--", ...
        "LineWidth", 1.0);

    %% Draw local coordinate axes
    plot( ...
        graphics.topAxes, ...
        [-lidarRange, lidarRange], ...
        [0, 0], ...
        "Color", [0.35, 0.35, 0.35], ...
        "LineStyle", ":");

    plot( ...
        graphics.topAxes, ...
        [0, 0], ...
        [-lidarRange, lidarRange], ...
        "Color", [0.35, 0.35, 0.35], ...
        "LineStyle", ":");

    %% Draw drone marker at local origin
    graphics.topDrone = plot( ...
        graphics.topAxes, ...
        0, ...
        0, ...
        "^", ...
        "MarkerSize", 10, ...
        "MarkerFaceColor", [0.20, 1.00, 0.30], ...
        "MarkerEdgeColor", "black");

    %% Create local LiDAR hit points
    graphics.topHits = scatter( ...
        graphics.topAxes, ...
        NaN, ...
        NaN, ...
        20, ...
        "filled", ...
        "MarkerFaceColor", [1.00, 0.25, 0.10], ...
        "MarkerEdgeColor", "none");
end