function updateLidarGraphics(graphics, lidar, drone)
%UPDATELIDARGRAPHICS Update the LiDAR visualization.

    validPoints = lidar.hitPoints(lidar.hitDetected, :);

    if isempty(validPoints)
        set( ...
            graphics.hitPoints3D, ...
            "XData", NaN, ...
            "YData", NaN, ...
            "ZData", NaN);
    else
        set( ...
            graphics.hitPoints3D, ...
            "XData", validPoints(:,1), ...
            "YData", validPoints(:,2), ...
            "ZData", validPoints(:,3));
    end

    rayX = [];
    rayY = [];
    rayZ = [];

    detectedIndices = find(lidar.hitDetected);

    % Display only a limited number of rays to keep the figure readable.
    maximumDisplayedRays = 30;

    if numel(detectedIndices) > maximumDisplayedRays
        selectedLocations = round(linspace( ...
            1, ...
            numel(detectedIndices), ...
            maximumDisplayedRays));

        detectedIndices = detectedIndices(selectedLocations);
    end

    for index = detectedIndices

        rayX = [
            rayX, ...
            drone.position(1), ...
            lidar.hitPoints(index,1), ...
            NaN
        ];

        rayY = [
            rayY, ...
            drone.position(2), ...
            lidar.hitPoints(index,2), ...
            NaN
        ];

        rayZ = [
            rayZ, ...
            drone.position(3), ...
            lidar.hitPoints(index,3), ...
            NaN
        ];
    end

    set( ...
        graphics.rayLines, ...
        "XData", rayX, ...
        "YData", rayY, ...
        "ZData", rayZ);

    localX = ...
        lidar.ranges .* cos(lidar.relativeAngles);

    localY = ...
        lidar.ranges .* sin(lidar.relativeAngles);

    localX = localX(lidar.hitDetected);
    localY = localY(lidar.hitDetected);

    if isempty(localX)
        set( ...
            graphics.topHits, ...
            "XData", NaN, ...
            "YData", NaN);
    else
        set( ...
            graphics.topHits, ...
            "XData", localX, ...
            "YData", localY);
    end
end