function graphics = initializeFPVGraphics(mainFigure, config)
%INITIALIZEFPVGRAPHICS Create the forward-facing FPV camera display.
%
% This display is a camera-projection view rather than a second 3D axes.
% World objects are transformed into the drone camera frame and projected
% onto a normalized two-dimensional screen.

    %% Create FPV axes
    graphics.axes = axes( ...
        "Parent", mainFigure, ...
        "Position", [0.65, 0.305, 0.33, 0.235], ...
        "Color", [0.04, 0.06, 0.08]);

    hold(graphics.axes, "on");
    box(graphics.axes, "on");

    axis(graphics.axes, "manual");

    xlim( ...
        graphics.axes, ...
        config.fpv.screenXLimits);

    ylim( ...
        graphics.axes, ...
        config.fpv.screenYLimits);

    graphics.axes.XTick = [];
    graphics.axes.YTick = [];

    graphics.axes.XColor = [0.45, 0.55, 0.62];
    graphics.axes.YColor = [0.45, 0.55, 0.62];

    title( ...
        graphics.axes, ...
        "FORWARD FPV CAMERA", ...
        "Color", [0.90, 0.95, 1.00], ...
        "FontWeight", "bold", ...
        "FontSize", 9);

    %% Sky and ground background
    graphics.sky = patch( ...
        graphics.axes, ...
        [-1, 1, 1, -1], ...
        [0, 0, 1, 1], ...
        [0.18, 0.28, 0.38], ...
        "EdgeColor", "none");

    graphics.ground = patch( ...
        graphics.axes, ...
        [-1, 1, 1, -1], ...
        [-1, -1, 0, 0], ...
        [0.16, 0.17, 0.18], ...
        "EdgeColor", "none");

    %% Horizon line
    graphics.horizon = plot( ...
        graphics.axes, ...
        [-1, 1], ...
        [0, 0], ...
        "-", ...
        "Color", [0.80, 0.85, 0.90], ...
        "LineWidth", 1.0);

    %% Flight corridor
    graphics.corridorLeft = plot( ...
        graphics.axes, ...
        [-0.65, -0.12], ...
        [-1.0, 0.0], ...
        "--", ...
        "Color", [0.15, 0.85, 1.00], ...
        "LineWidth", 1.0);

    graphics.corridorRight = plot( ...
        graphics.axes, ...
        [0.65, 0.12], ...
        [-1.0, 0.0], ...
        "--", ...
        "Color", [0.15, 0.85, 1.00], ...
        "LineWidth", 1.0);

    %% Center reticle
    graphics.reticleHorizontal = plot( ...
        graphics.axes, ...
        [-0.08, 0.08], ...
        [0, 0], ...
        "-", ...
        "Color", [0.20, 1.00, 0.30], ...
        "LineWidth", 1.5);

    graphics.reticleVertical = plot( ...
        graphics.axes, ...
        [0, 0], ...
        [-0.08, 0.08], ...
        "-", ...
        "Color", [0.20, 1.00, 0.30], ...
        "LineWidth", 1.5);

    %% Projected buildings
    graphics.buildingPatches = gobjects(20, 1);

    for objectIndex = 1:numel(graphics.buildingPatches)

        graphics.buildingPatches(objectIndex) = patch( ...
            graphics.axes, ...
            NaN, ...
            NaN, ...
            [0.48, 0.50, 0.53], ...
            "FaceAlpha", 0.85, ...
            "EdgeColor", [0.08, 0.08, 0.08], ...
            "Visible", "off");
    end

    %% Projected bird
    graphics.birdMarker = plot( ...
        graphics.axes, ...
        NaN, ...
        NaN, ...
        "o", ...
        "MarkerSize", 11, ...
        "MarkerFaceColor", [1.00, 0.40, 0.10], ...
        "MarkerEdgeColor", [1.00, 0.90, 0.20], ...
        "LineWidth", 1.2, ...
        "Visible", "off");

    graphics.birdLabel = text( ...
        graphics.axes, ...
        0, ...
        0, ...
        "BIRD", ...
        "Color", [1.00, 0.65, 0.15], ...
        "FontWeight", "bold", ...
        "FontSize", 8, ...
        "HorizontalAlignment", "center", ...
        "Visible", "off");

    %% Target waypoint marker
    graphics.targetMarker = plot( ...
        graphics.axes, ...
        NaN, ...
        NaN, ...
        "p", ...
        "MarkerSize", 13, ...
        "MarkerFaceColor", [1.00, 0.85, 0.10], ...
        "MarkerEdgeColor", "black", ...
        "Visible", "off");

    graphics.targetLabel = text( ...
        graphics.axes, ...
        0, ...
        0, ...
        "TARGET", ...
        "Color", [1.00, 0.90, 0.25], ...
        "FontWeight", "bold", ...
        "FontSize", 7, ...
        "HorizontalAlignment", "center", ...
        "Visible", "off");

    %% HUD text
    graphics.headingText = text( ...
        graphics.axes, ...
        -0.95, ...
        0.90, ...
        "", ...
        "Color", [0.20, 1.00, 0.35], ...
        "FontName", "Consolas", ...
        "FontSize", 8, ...
        "VerticalAlignment", "top");

    graphics.altitudeText = text( ...
        graphics.axes, ...
        0.95, ...
        0.90, ...
        "", ...
        "Color", [0.20, 1.00, 0.35], ...
        "FontName", "Consolas", ...
        "FontSize", 8, ...
        "HorizontalAlignment", "right", ...
        "VerticalAlignment", "top");

    graphics.speedText = text( ...
        graphics.axes, ...
        -0.95, ...
        -0.90, ...
        "", ...
        "Color", [0.20, 1.00, 0.35], ...
        "FontName", "Consolas", ...
        "FontSize", 8, ...
        "VerticalAlignment", "bottom");

    graphics.distanceText = text( ...
        graphics.axes, ...
        0.95, ...
        -0.90, ...
        "", ...
        "Color", [0.20, 1.00, 0.35], ...
        "FontName", "Consolas", ...
        "FontSize", 8, ...
        "HorizontalAlignment", "right", ...
        "VerticalAlignment", "bottom");

    graphics.warningText = text( ...
        graphics.axes, ...
        0, ...
        0.72, ...
        "", ...
        "Color", [1.00, 0.25, 0.10], ...
        "BackgroundColor", [0.10, 0.08, 0.06], ...
        "FontWeight", "bold", ...
        "FontSize", 10, ...
        "HorizontalAlignment", "center", ...
        "Margin", 3, ...
        "Visible", "off");
end