function fpv = updateFPVGraphics( ...
    graphics, drone, targetPosition, environment, bird, lidar, config)
%UPDATEFPVGRAPHICS Update the simulated forward-facing camera view.
%
% Camera coordinate convention:
%
%   Camera X = forward
%   Camera Y = right
%   Camera Z = upward
%
% World convention:
%
%   World X and Y form the horizontal plane.
%   World Z points upward.
%
% Perspective projection:
%
%   screen X = camera-right distance / forward distance
%   screen Y = upward distance / forward distance
%
% The camera-right vector is selected so that objects physically on the
% drone's right appear on the right side of the FPV screen.

    %% Initialize FPV diagnostic output
    fpv.visibleBuildingCount = 0;
    fpv.birdVisible = false;
    fpv.targetVisible = false;
    fpv.nearestForwardObstacle = Inf;

    %% Camera coordinate axes
    forwardDirection = [
        cos(drone.yaw), ...
        sin(drone.yaw), ...
        0
    ];

    % Correct camera-right direction.
    %
    % At yaw = 0:
    %   Forward = +X
    %   Right   = -Y
    %
    % Therefore, an object moving from +Y toward -Y appears to travel
    % from the left side of the FPV image toward the right side.
    rightDirection = [
         sin(drone.yaw), ...
        -cos(drone.yaw), ...
         0
    ];

    upwardDirection = [0, 0, 1];

    %% Camera position
    cameraPosition = ...
        drone.position + ...
        config.fpv.cameraForwardOffset * forwardDirection + ...
        [0, 0, config.fpv.cameraVerticalOffset];

    %% Projection constants
    horizontalTangent = ...
        tan(config.fpv.horizontalFOV / 2);

    verticalTangent = ...
        tan(config.fpv.verticalFOV / 2);

    %% Horizon movement from roll and pitch
    horizonVerticalOffset = ...
        max( ...
            -0.65, ...
            min(0.65, -1.4 * drone.pitch));

    % With the corrected screen-right direction, this sign produces a
    % physically consistent roll indication in the FPV display.
    horizonSlope = ...
        -tan(drone.roll);

    horizonX = [-1, 1];

    horizonY = [
        horizonVerticalOffset - horizonSlope, ...
        horizonVerticalOffset + horizonSlope
    ];

    set( ...
        graphics.horizon, ...
        "XData", horizonX, ...
        "YData", horizonY);

    %% Update sky-ground boundary
    set( ...
        graphics.sky, ...
        "YData", [ ...
            horizonY(1), ...
            horizonY(2), ...
            1, ...
            1]);

    set( ...
        graphics.ground, ...
        "YData", [ ...
            -1, ...
            -1, ...
            horizonY(2), ...
            horizonY(1)]);

    %% Hide all building patches before redrawing
    for patchIndex = 1:numel(graphics.buildingPatches)

        graphics.buildingPatches(patchIndex).Visible = ...
            "off";
    end

    %% Project static buildings
    numberOfBuildings = ...
        size(environment.buildingCenters, 1);

    visiblePatchIndex = 1;

    for buildingIndex = 1:numberOfBuildings

        centerXY = ...
            environment.buildingCenters( ...
                buildingIndex, :);

        dimensions = ...
            environment.buildingDimensions( ...
                buildingIndex, :);

        buildingCenter = [
            centerXY(1), ...
            centerXY(2), ...
            dimensions(3) / 2
        ];

        relativeVector = ...
            buildingCenter - cameraPosition;

        forwardDistance = dot( ...
            relativeVector, ...
            forwardDirection);

        rightDistance = dot( ...
            relativeVector, ...
            rightDirection);

        verticalDistance = dot( ...
            relativeVector, ...
            upwardDirection);

        %% Reject buildings behind or too far from camera
        if forwardDistance <= 0.20 || ...
                forwardDistance > ...
                config.fpv.maximumViewDistance

            continue;
        end

        %% Project building center
        screenCenterX = ...
            rightDistance / ...
            (forwardDistance * horizontalTangent);

        screenCenterY = ...
            verticalDistance / ...
            (forwardDistance * verticalTangent);

        %% Approximate projected size
        projectedHalfWidth = ...
            dimensions(2) / ...
            (2 * forwardDistance * horizontalTangent);

        projectedHalfHeight = ...
            dimensions(3) / ...
            (2 * forwardDistance * verticalTangent);

        %% Reject buildings outside the screen
        if abs(screenCenterX) - projectedHalfWidth > 1 || ...
                abs(screenCenterY) - projectedHalfHeight > 1

            continue;
        end

        if visiblePatchIndex > ...
                numel(graphics.buildingPatches)

            break;
        end

        objectX = [
            screenCenterX - projectedHalfWidth, ...
            screenCenterX + projectedHalfWidth, ...
            screenCenterX + projectedHalfWidth, ...
            screenCenterX - projectedHalfWidth
        ];

        objectY = [
            screenCenterY - projectedHalfHeight, ...
            screenCenterY - projectedHalfHeight, ...
            screenCenterY + projectedHalfHeight, ...
            screenCenterY + projectedHalfHeight
        ];

        %% Apply simple depth shading
        depthShade = max( ...
            0.22, ...
            0.70 - 0.025 * forwardDistance);

        set( ...
            graphics.buildingPatches(visiblePatchIndex), ...
            "XData", objectX, ...
            "YData", objectY, ...
            "FaceColor", [ ...
                depthShade, ...
                depthShade, ...
                depthShade + 0.04], ...
            "Visible", "on");

        visiblePatchIndex = ...
            visiblePatchIndex + 1;

        fpv.visibleBuildingCount = ...
            fpv.visibleBuildingCount + 1;
    end

    %% Project active target waypoint
    [ ...
        targetVisible, ...
        targetScreenX, ...
        targetScreenY, ...
        targetDistance ...
    ] = projectPointToCamera( ...
        targetPosition, ...
        cameraPosition, ...
        forwardDirection, ...
        rightDirection, ...
        upwardDirection, ...
        horizontalTangent, ...
        verticalTangent, ...
        config.fpv.maximumViewDistance);

    fpv.targetVisible = ...
        targetVisible;

    if targetVisible

        set( ...
            graphics.targetMarker, ...
            "XData", targetScreenX, ...
            "YData", targetScreenY, ...
            "Visible", "on");

        set( ...
            graphics.targetLabel, ...
            "Position", [ ...
                targetScreenX, ...
                targetScreenY + 0.12, ...
                0], ...
            "String", sprintf( ...
                "TARGET %.1f m", ...
                targetDistance), ...
            "Visible", "on");

    else

        graphics.targetMarker.Visible = "off";
        graphics.targetLabel.Visible = "off";
    end

    %% Project dynamic bird
    if bird.active

        [ ...
            birdVisible, ...
            birdScreenX, ...
            birdScreenY, ...
            birdDistance ...
        ] = projectPointToCamera( ...
            bird.position, ...
            cameraPosition, ...
            forwardDirection, ...
            rightDirection, ...
            upwardDirection, ...
            horizontalTangent, ...
            verticalTangent, ...
            config.fpv.maximumViewDistance);

        fpv.birdVisible = ...
            birdVisible;

        if birdVisible

            markerSize = min( ...
                20, ...
                max( ...
                    7, ...
                    28 / max(birdDistance, 0.5)));

            set( ...
                graphics.birdMarker, ...
                "XData", birdScreenX, ...
                "YData", birdScreenY, ...
                "MarkerSize", markerSize, ...
                "Visible", "on");

            set( ...
                graphics.birdLabel, ...
                "Position", [ ...
                    birdScreenX, ...
                    birdScreenY + 0.14, ...
                    0], ...
                "String", sprintf( ...
                    "BIRD %.1f m", ...
                    birdDistance), ...
                "Visible", "on");

        else

            graphics.birdMarker.Visible = "off";
            graphics.birdLabel.Visible = "off";
        end

    else

        graphics.birdMarker.Visible = "off";
        graphics.birdLabel.Visible = "off";
    end

    %% Determine nearest forward LiDAR obstacle
    validIndices = ...
        find(lidar.hitDetected);

    for detectionIndex = validIndices

        rayDirection = [
            cos(lidar.worldAngles(detectionIndex)), ...
            sin(lidar.worldAngles(detectionIndex)), ...
            0
        ];

        forwardAlignment = dot( ...
            rayDirection, ...
            forwardDirection);

        if forwardAlignment > 0.70

            fpv.nearestForwardObstacle = min( ...
                fpv.nearestForwardObstacle, ...
                lidar.ranges(detectionIndex));
        end
    end

    %% Update HUD heading
    headingDegrees = mod( ...
        rad2deg(drone.yaw), ...
        360);

    set( ...
        graphics.headingText, ...
        "String", sprintf( ...
            "HDG %03.0f°", ...
            headingDegrees));

    %% Update HUD altitude
    set( ...
        graphics.altitudeText, ...
        "String", sprintf( ...
            "ALT %.1f m", ...
            drone.position(3)));

    %% Update HUD ground speed
    set( ...
        graphics.speedText, ...
        "String", sprintf( ...
            "GS %.2f m/s", ...
            norm(drone.velocity)));

    %% Update HUD target distance
    set( ...
        graphics.distanceText, ...
        "String", sprintf( ...
            "TGT %.1f m", ...
            norm(targetPosition - drone.position)));

    %% Warning logic
    if fpv.nearestForwardObstacle < ...
            config.fpv.dangerDistance

        set( ...
            graphics.warningText, ...
            "String", "COLLISION WARNING", ...
            "Color", [1.00, 0.15, 0.10], ...
            "Visible", "on");

    elseif fpv.nearestForwardObstacle < ...
            config.fpv.cautionDistance

        set( ...
            graphics.warningText, ...
            "String", "OBSTACLE AHEAD", ...
            "Color", [1.00, 0.75, 0.10], ...
            "Visible", "on");

    elseif fpv.birdVisible

        set( ...
            graphics.warningText, ...
            "String", "DYNAMIC OBJECT", ...
            "Color", [1.00, 0.65, 0.10], ...
            "Visible", "on");

    else

        graphics.warningText.Visible = "off";
    end
end


function [visible, screenX, screenY, distance] = ...
    projectPointToCamera( ...
        worldPoint, ...
        cameraPosition, ...
        forwardDirection, ...
        rightDirection, ...
        upwardDirection, ...
        horizontalTangent, ...
        verticalTangent, ...
        maximumDistance)
%PROJECTPOINTTOCAMERA Project one world point onto the FPV screen.
%
% Positive screen X represents the drone's physical right side.
% Negative screen X represents the drone's physical left side.

    relativeVector = ...
        worldPoint - cameraPosition;

    forwardDistance = dot( ...
        relativeVector, ...
        forwardDirection);

    rightDistance = dot( ...
        relativeVector, ...
        rightDirection);

    verticalDistance = dot( ...
        relativeVector, ...
        upwardDirection);

    distance = ...
        norm(relativeVector);

    %% Reject objects behind or beyond maximum camera distance
    if forwardDistance <= 0.15 || ...
            distance > maximumDistance

        visible = false;
        screenX = NaN;
        screenY = NaN;

        return;
    end

    %% Perspective projection
    screenX = ...
        rightDistance / ...
        (forwardDistance * horizontalTangent);

    screenY = ...
        verticalDistance / ...
        (forwardDistance * verticalTangent);

    %% Check whether projected point is inside the FPV screen
    visible = ...
        abs(screenX) <= 1 && ...
        abs(screenY) <= 1;
end